// Code generated by cmd/generator. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"

	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/client"
)

var (
	_ resource.Resource                = &encryption_keyResource{}
	_ resource.ResourceWithConfigure   = &encryption_keyResource{}
	_ resource.ResourceWithImportState = &encryption_keyResource{}
)

func NewEncryptionKeyResource() resource.Resource {
	return &encryption_keyResource{}
}

type encryption_keyResource struct {
	client *client.Client
}

type encryption_keyModel struct {
	ID                    types.String `tfsdk:"id"`
	Handle                types.String `tfsdk:"handle"`
	Format                types.String `tfsdk:"format"`
	Key                   types.String `tfsdk:"key"`
	Name                  types.String `tfsdk:"name"`
	Maxversions           types.Int64  `tfsdk:"maxversions"`
	Billable              types.Bool   `tfsdk:"billable"`
	Currentversion        types.Int64  `tfsdk:"currentversion"`
	Keybits               types.Int64  `tfsdk:"keybits"`
	Managedbyresourceid   types.String `tfsdk:"managedbyresourceid"`
	Managedbyresourcetype types.String `tfsdk:"managedbyresourcetype"`
	Organisation          types.String `tfsdk:"organisation"`
}

func (r *encryption_keyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_encryption_key"
}

func (r *encryption_keyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Bahriya encryption_key.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"handle": schema.StringAttribute{
				Required:    true,
				Description: "DNS-1123 compliant: lowercase alphanumeric and hyphens only.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"format": schema.StringAttribute{
				Required:    true,
				Description: "Key encoding format: base64, hex, or raw.",
			},
			"key": schema.StringAttribute{
				Required:    true,
				Sensitive:   true,
				Description: "The raw encryption key (base64 or hex encoded). Never returned on read.",
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"maxversions": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"billable": schema.BoolAttribute{
				Computed: true,
			},
			"currentversion": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"keybits": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourceid": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourcetype": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organisation": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *encryption_keyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *encryption_keyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan encryption_keyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	handle := plan.Handle.ValueString()
	exists, err := r.client.HandleExists(ctx, "encryption_key", handle)
	if err != nil {
		resp.Diagnostics.AddError("Handle existence check failed", err.Error())
		return
	}
	if exists {
		resp.Diagnostics.AddError(
			"Handle already in use",
			fmt.Sprintf("A encryption_key with handle %q already exists in this organisation. Handles cannot be reused.", handle),
		)
		return
	}

	body, diags := planToEncryptionKeyPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPost, fmt.Sprintf("/organisations/%s/encryption_keys", r.client.OrganisationID()), body)
	if err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status from Create", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	var id string
	if err := json.Unmarshal(data, &id); err != nil {
		resp.Diagnostics.AddError("Decode created id failed", err.Error())
		return
	}

	state, diags := r.fetch(ctx, id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	state.Key = knownValue(plan.Key, types.StringNull())

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *encryption_keyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state encryption_keyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	if diags.HasError() {
		if diagsContainNotFound(diags) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.Append(diags...)
		return
	}
	fresh.Key = state.Key

	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *encryption_keyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state encryption_keyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if encryption_keyModelsEqual(plan, state) {
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	}

	body, diags := planToEncryptionKeyPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPut, fmt.Sprintf("/organisations/%s/encryption_keys/%s", r.client.OrganisationID(), state.ID.ValueString()), body)
	if err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	if status != http.StatusOK {
		// Surface the API's message body (e.g. a 409 explaining a network policy is
		// already project-attached) so the user can act on it, not just the code.
		resp.Diagnostics.AddError("Unexpected status from Update", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	fresh.Key = knownValue(plan.Key, state.Key)
	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *encryption_keyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state encryption_keyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, status, err := r.client.Do(ctx, http.MethodDelete, fmt.Sprintf("/organisations/%s/encryption_keys/%s", r.client.OrganisationID(), state.ID.ValueString()), nil)
	if err != nil && status != http.StatusNotFound {
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

func (r *encryption_keyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("id"), req.ID)...)
}

func (r *encryption_keyResource) fetch(ctx context.Context, id string) (encryption_keyModel, diagnostics) {
	var diags diagnostics
	data, status, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/encryption_keys/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		if status == http.StatusNotFound {
			diags.AddError("not_found", "resource was deleted out-of-band")
			return encryption_keyModel{}, diags
		}
		diags.AddError("Fetch failed", err.Error())
		return encryption_keyModel{}, diags
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		diags.AddError("Decode fetch response failed", err.Error())
		return encryption_keyModel{}, diags
	}
	return apiToEncryptionKeyModel(raw), diags
}

func planToEncryptionKeyPayload(ctx context.Context, m *encryption_keyModel) (map[string]any, diagnostics) {
	var diags diagnostics
	out := map[string]any{}
	if !m.Handle.IsNull() && !m.Handle.IsUnknown() {
		out["handle"] = m.Handle.ValueString()
	}
	if !m.Format.IsNull() && !m.Format.IsUnknown() {
		out["format"] = m.Format.ValueString()
	}
	if !m.Key.IsNull() && !m.Key.IsUnknown() {
		out["key"] = m.Key.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out["name"] = m.Name.ValueString()
	}
	if !m.Maxversions.IsNull() && !m.Maxversions.IsUnknown() {
		out["maxversions"] = m.Maxversions.ValueInt64()
	}
	return out, diags
}

func apiToEncryptionKeyModel(raw map[string]any) encryption_keyModel {
	m := encryption_keyModel{}
	if v, ok := raw["id"].(string); ok {
		m.ID = types.StringValue(v)
	} else {
		m.ID = types.StringNull()
	}
	if v, ok := raw["handle"].(string); ok {
		m.Handle = types.StringValue(v)
	} else {
		m.Handle = types.StringNull()
	}
	if v, ok := raw["format"].(string); ok {
		m.Format = types.StringValue(v)
	} else {
		m.Format = types.StringNull()
	}
	if v, ok := raw["key"].(string); ok {
		m.Key = types.StringValue(v)
	} else {
		m.Key = types.StringNull()
	}
	if v, ok := raw["name"].(string); ok {
		m.Name = types.StringValue(v)
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := raw["maxversions"].(float64); ok {
		m.Maxversions = types.Int64Value(int64(v))
	} else {
		m.Maxversions = types.Int64Null()
	}
	if v, ok := raw["billable"].(bool); ok {
		m.Billable = types.BoolValue(v)
	} else {
		m.Billable = types.BoolNull()
	}
	if v, ok := raw["currentversion"].(float64); ok {
		m.Currentversion = types.Int64Value(int64(v))
	} else {
		m.Currentversion = types.Int64Null()
	}
	if v, ok := raw["keybits"].(float64); ok {
		m.Keybits = types.Int64Value(int64(v))
	} else {
		m.Keybits = types.Int64Null()
	}
	if v, ok := raw["managedbyresourceid"].(string); ok {
		m.Managedbyresourceid = types.StringValue(v)
	} else {
		m.Managedbyresourceid = types.StringNull()
	}
	if v, ok := raw["managedbyresourcetype"].(string); ok {
		m.Managedbyresourcetype = types.StringValue(v)
	} else {
		m.Managedbyresourcetype = types.StringNull()
	}
	if v, ok := raw["organisation"].(string); ok {
		m.Organisation = types.StringValue(v)
	} else {
		m.Organisation = types.StringNull()
	}
	return m
}

func encryption_keyModelsEqual(a, b encryption_keyModel) bool {
	if !a.Handle.Equal(b.Handle) {
		return false
	}
	if !a.Format.Equal(b.Format) {
		return false
	}
	if !a.Key.Equal(b.Key) {
		return false
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	if !a.Maxversions.Equal(b.Maxversions) {
		return false
	}
	return true
}
