// Code generated by cmd/generator. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"

	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/client"
)

var (
	_ resource.Resource                = &gpg_keypairResource{}
	_ resource.ResourceWithConfigure   = &gpg_keypairResource{}
	_ resource.ResourceWithImportState = &gpg_keypairResource{}
)

func NewGpgKeypairResource() resource.Resource {
	return &gpg_keypairResource{}
}

type gpg_keypairResource struct {
	client *client.Client
}

type gpg_keypairModel struct {
	ID                    types.String `tfsdk:"id"`
	Handle                types.String `tfsdk:"handle"`
	Name                  types.String `tfsdk:"name"`
	Maxversions           types.Int64  `tfsdk:"maxversions"`
	PrivateKey            types.String `tfsdk:"private_key"`
	PublicKey             types.String `tfsdk:"public_key"`
	Algorithm             types.String `tfsdk:"algorithm"`
	Billable              types.Bool   `tfsdk:"billable"`
	Currentversion        types.Int64  `tfsdk:"currentversion"`
	KeyBits               types.Int64  `tfsdk:"key_bits"`
	KeyID                 types.String `tfsdk:"key_id"`
	Managedbyresourceid   types.String `tfsdk:"managedbyresourceid"`
	Managedbyresourcetype types.String `tfsdk:"managedbyresourcetype"`
	Organisation          types.String `tfsdk:"organisation"`
	Uid                   types.String `tfsdk:"uid"`
}

func (r *gpg_keypairResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gpg_keypair"
}

func (r *gpg_keypairResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Bahriya gpg_keypair.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"handle": schema.StringAttribute{
				Required:    true,
				Description: "DNS-1123 compliant: lowercase alphanumeric and hyphens only.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"maxversions": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"private_key": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Sensitive:   true,
				Description: "ASCII-armored PGP private key. Never returned on read.",
			},
			"public_key": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Sensitive:   true,
				Description: "ASCII-armored PGP public key.",
			},
			"algorithm": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"billable": schema.BoolAttribute{
				Computed: true,
			},
			"currentversion": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"key_bits": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"key_id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourceid": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourcetype": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organisation": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"uid": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *gpg_keypairResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *gpg_keypairResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan gpg_keypairModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	handle := plan.Handle.ValueString()
	exists, err := r.client.HandleExists(ctx, "gpg_keypair", handle)
	if err != nil {
		resp.Diagnostics.AddError("Handle existence check failed", err.Error())
		return
	}
	if exists {
		resp.Diagnostics.AddError(
			"Handle already in use",
			fmt.Sprintf("A gpg_keypair with handle %q already exists in this organisation. Handles cannot be reused.", handle),
		)
		return
	}

	body, diags := planToGpgKeypairPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPost, fmt.Sprintf("/organisations/%s/gpg_keypairs", r.client.OrganisationID()), body)
	if err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status from Create", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	var id string
	if err := json.Unmarshal(data, &id); err != nil {
		resp.Diagnostics.AddError("Decode created id failed", err.Error())
		return
	}

	state, diags := r.fetch(ctx, id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	state.PrivateKey = plan.PrivateKey
	state.PublicKey = plan.PublicKey

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *gpg_keypairResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state gpg_keypairModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	if diags.HasError() {
		if diagsContainNotFound(diags) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.Append(diags...)
		return
	}
	fresh.PrivateKey = state.PrivateKey
	fresh.PublicKey = state.PublicKey

	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *gpg_keypairResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state gpg_keypairModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if gpg_keypairModelsEqual(plan, state) {
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	}

	body, diags := planToGpgKeypairPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	_, status, err := r.client.Do(ctx, http.MethodPut, fmt.Sprintf("/organisations/%s/gpg_keypairs/%s", r.client.OrganisationID(), state.ID.ValueString()), body)
	if err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	if status != http.StatusOK {
		resp.Diagnostics.AddError("Unexpected status from Update", fmt.Sprintf("HTTP %d", status))
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	fresh.PrivateKey = plan.PrivateKey
	fresh.PublicKey = plan.PublicKey
	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *gpg_keypairResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state gpg_keypairModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, status, err := r.client.Do(ctx, http.MethodDelete, fmt.Sprintf("/organisations/%s/gpg_keypairs/%s", r.client.OrganisationID(), state.ID.ValueString()), nil)
	if err != nil && status != http.StatusNotFound {
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

func (r *gpg_keypairResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("id"), req.ID)...)
}

func (r *gpg_keypairResource) fetch(ctx context.Context, id string) (gpg_keypairModel, diagnostics) {
	var diags diagnostics
	data, status, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/gpg_keypairs/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		if status == http.StatusNotFound {
			diags.AddError("not_found", "resource was deleted out-of-band")
			return gpg_keypairModel{}, diags
		}
		diags.AddError("Fetch failed", err.Error())
		return gpg_keypairModel{}, diags
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		diags.AddError("Decode fetch response failed", err.Error())
		return gpg_keypairModel{}, diags
	}
	return apiToGpgKeypairModel(raw), diags
}

func planToGpgKeypairPayload(ctx context.Context, m *gpg_keypairModel) (map[string]any, diagnostics) {
	var diags diagnostics
	out := map[string]any{}
	if !m.Handle.IsNull() && !m.Handle.IsUnknown() {
		out["handle"] = m.Handle.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out["name"] = m.Name.ValueString()
	}
	if !m.Maxversions.IsNull() && !m.Maxversions.IsUnknown() {
		out["maxversions"] = m.Maxversions.ValueInt64()
	}
	if !m.PrivateKey.IsNull() && !m.PrivateKey.IsUnknown() {
		out["private_key"] = m.PrivateKey.ValueString()
	}
	if !m.PublicKey.IsNull() && !m.PublicKey.IsUnknown() {
		out["public_key"] = m.PublicKey.ValueString()
	}
	return out, diags
}

func apiToGpgKeypairModel(raw map[string]any) gpg_keypairModel {
	m := gpg_keypairModel{}
	if v, ok := raw["id"].(string); ok {
		m.ID = types.StringValue(v)
	} else {
		m.ID = types.StringNull()
	}
	if v, ok := raw["handle"].(string); ok {
		m.Handle = types.StringValue(v)
	} else {
		m.Handle = types.StringNull()
	}
	if v, ok := raw["name"].(string); ok {
		m.Name = types.StringValue(v)
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := raw["maxversions"].(float64); ok {
		m.Maxversions = types.Int64Value(int64(v))
	} else {
		m.Maxversions = types.Int64Null()
	}
	if v, ok := raw["private_key"].(string); ok {
		m.PrivateKey = types.StringValue(v)
	} else {
		m.PrivateKey = types.StringNull()
	}
	if v, ok := raw["public_key"].(string); ok {
		m.PublicKey = types.StringValue(v)
	} else {
		m.PublicKey = types.StringNull()
	}
	if v, ok := raw["algorithm"].(string); ok {
		m.Algorithm = types.StringValue(v)
	} else {
		m.Algorithm = types.StringNull()
	}
	if v, ok := raw["billable"].(bool); ok {
		m.Billable = types.BoolValue(v)
	} else {
		m.Billable = types.BoolNull()
	}
	if v, ok := raw["currentversion"].(float64); ok {
		m.Currentversion = types.Int64Value(int64(v))
	} else {
		m.Currentversion = types.Int64Null()
	}
	if v, ok := raw["key_bits"].(float64); ok {
		m.KeyBits = types.Int64Value(int64(v))
	} else {
		m.KeyBits = types.Int64Null()
	}
	if v, ok := raw["key_id"].(string); ok {
		m.KeyID = types.StringValue(v)
	} else {
		m.KeyID = types.StringNull()
	}
	if v, ok := raw["managedbyresourceid"].(string); ok {
		m.Managedbyresourceid = types.StringValue(v)
	} else {
		m.Managedbyresourceid = types.StringNull()
	}
	if v, ok := raw["managedbyresourcetype"].(string); ok {
		m.Managedbyresourcetype = types.StringValue(v)
	} else {
		m.Managedbyresourcetype = types.StringNull()
	}
	if v, ok := raw["organisation"].(string); ok {
		m.Organisation = types.StringValue(v)
	} else {
		m.Organisation = types.StringNull()
	}
	if v, ok := raw["uid"].(string); ok {
		m.Uid = types.StringValue(v)
	} else {
		m.Uid = types.StringNull()
	}
	return m
}

func gpg_keypairModelsEqual(a, b gpg_keypairModel) bool {
	if !a.Handle.Equal(b.Handle) {
		return false
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	if !a.Maxversions.Equal(b.Maxversions) {
		return false
	}
	if !a.PrivateKey.Equal(b.PrivateKey) {
		return false
	}
	if !a.PublicKey.Equal(b.PublicKey) {
		return false
	}
	return true
}
