// Code generated by cmd/generator. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"
	"time"

	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/client"
	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/lifecycle"
)

var (
	_ resource.Resource                = &memcachedResource{}
	_ resource.ResourceWithConfigure   = &memcachedResource{}
	_ resource.ResourceWithImportState = &memcachedResource{}
)

func NewMemcachedResource() resource.Resource {
	return &memcachedResource{}
}

type memcachedResource struct {
	client *client.Client
}

type memcachedModel struct {
	ID                 types.String `tfsdk:"id"`
	Handle             types.String `tfsdk:"handle"`
	Activeregions      types.List   `tfsdk:"activeregions"`
	Memorymb           types.Int64  `tfsdk:"memorymb"`
	Name               types.String `tfsdk:"name"`
	Maxconnections     types.Int64  `tfsdk:"maxconnections"`
	Maxitemsizemb      types.Int64  `tfsdk:"maxitemsizemb"`
	Nodes              types.Int64  `tfsdk:"nodes"`
	Project            types.String `tfsdk:"project"`
	Threads            types.Int64  `tfsdk:"threads"`
	Managedbycontainer types.String `tfsdk:"managedbycontainer"`
	Organisation       types.String `tfsdk:"organisation"`
	Projectname        types.String `tfsdk:"projectname"`
	Status             types.String `tfsdk:"status"`
}

func (r *memcachedResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_memcached"
}

func (r *memcachedResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Bahriya memcached.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"handle": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"activeregions": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
			},
			"memorymb": schema.Int64Attribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"maxconnections": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"maxitemsizemb": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Maximum item size in MB (memcached -I flag)",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"nodes": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"project": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"threads": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"managedbycontainer": schema.StringAttribute{
				Computed:    true,
				Description: "When set, this memcached instance is managed by the named container (proxy cache feature) and cannot be modified directly.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organisation": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"projectname": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"status": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *memcachedResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *memcachedResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan memcachedModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	handle := plan.Handle.ValueString()
	exists, err := r.client.HandleExists(ctx, "memcache", handle)
	if err != nil {
		resp.Diagnostics.AddError("Handle existence check failed", err.Error())
		return
	}
	if exists {
		resp.Diagnostics.AddError(
			"Handle already in use",
			fmt.Sprintf("A memcached with handle %q already exists in this organisation. Handles cannot be reused.", handle),
		)
		return
	}

	body, diags := planToMemcachedPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPost, fmt.Sprintf("/organisations/%s/memcached", r.client.OrganisationID()), body)
	if err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status from Create", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	var id string
	if err := json.Unmarshal(data, &id); err != nil {
		resp.Diagnostics.AddError("Decode created id failed", err.Error())
		return
	}

	createTimeout := 10 * time.Minute
	_, werr := lifecycle.WaitForStatus(ctx, func(ctx context.Context) (string, error) {
		fresh, d := r.fetch(ctx, id)
		if d.HasError() {
			return "", fmt.Errorf("fetch error during wait")
		}
		return fresh.Status.ValueString(), nil
	}, lifecycle.WaitOptions{
		Target:   "running",
		Terminal: []string{"error"},
		Timeout:  createTimeout,
	})
	if werr != nil {
		// Persist whatever state we can read so `terraform destroy` can clean
		// the partially-created resource. Without this the ID is lost on
		// Create failure and the resource leaks.
		if partial, d := r.fetch(ctx, id); !d.HasError() {
			resp.Diagnostics.Append(resp.State.Set(ctx, partial)...)
		}
		resp.Diagnostics.AddError("Resource did not reach ready status", werr.Error())
		return
	}

	state, diags := r.fetch(ctx, id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *memcachedResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state memcachedModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	if diags.HasError() {
		if diagsContainNotFound(diags) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.Append(diags...)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *memcachedResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state memcachedModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if memcachedModelsEqual(plan, state) {
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	}

	body, diags := planToMemcachedPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	_, status, err := r.client.Do(ctx, http.MethodPut, fmt.Sprintf("/organisations/%s/memcached/%s", r.client.OrganisationID(), state.ID.ValueString()), body)
	if err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	if status != http.StatusOK {
		resp.Diagnostics.AddError("Unexpected status from Update", fmt.Sprintf("HTTP %d", status))
		return
	}

	// After a PUT, status-bearing resources transition through a transient
	// "provisioning" state while the backend rolls out the change. Waiting
	// for a stable status here avoids "inconsistent result after apply" when
	// the post-PUT fetch races the rollout.
	updateTimeout := 10 * time.Minute
	_, werr := lifecycle.WaitForStatus(ctx, func(ctx context.Context) (string, error) {
		fresh, d := r.fetch(ctx, state.ID.ValueString())
		if d.HasError() {
			return "", fmt.Errorf("fetch error during wait")
		}
		return fresh.Status.ValueString(), nil
	}, lifecycle.WaitOptions{
		Target:   "running",
		Terminal: []string{"error"},
		Timeout:  updateTimeout,
	})
	if werr != nil {
		resp.Diagnostics.AddError("Resource did not settle after Update", werr.Error())
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *memcachedResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state memcachedModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, status, err := r.client.Do(ctx, http.MethodDelete, fmt.Sprintf("/organisations/%s/memcached/%s", r.client.OrganisationID(), state.ID.ValueString()), nil)
	if err != nil && status != http.StatusNotFound {
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}

	deleteTimeout := 10 * time.Minute
	_, werr := lifecycle.WaitForStatus(ctx, func(ctx context.Context) (string, error) {
		raw, ferr := r.fetchRaw(ctx, state.ID.ValueString())
		if ferr != nil {
			return "terminated", nil
		}
		if s, ok := raw["status"].(string); ok {
			return s, nil
		}
		return "terminated", nil
	}, lifecycle.WaitOptions{
		Target:  "terminated",
		Timeout: deleteTimeout,
	})
	if werr != nil {
		resp.Diagnostics.AddError("Resource did not reach terminated status", werr.Error())
		return
	}
}

func (r *memcachedResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("id"), req.ID)...)
}

func (r *memcachedResource) fetch(ctx context.Context, id string) (memcachedModel, diagnostics) {
	var diags diagnostics
	data, status, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/memcached/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		if status == http.StatusNotFound {
			diags.AddError("not_found", "resource was deleted out-of-band")
			return memcachedModel{}, diags
		}
		diags.AddError("Fetch failed", err.Error())
		return memcachedModel{}, diags
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		diags.AddError("Decode fetch response failed", err.Error())
		return memcachedModel{}, diags
	}
	return apiToMemcachedModel(raw), diags
}

func (r *memcachedResource) fetchRaw(ctx context.Context, id string) (map[string]any, error) {
	data, _, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/memcached/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		return nil, err
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	return raw, nil
}

func planToMemcachedPayload(ctx context.Context, m *memcachedModel) (map[string]any, diagnostics) {
	var diags diagnostics
	out := map[string]any{}
	if !m.Handle.IsNull() && !m.Handle.IsUnknown() {
		out["handle"] = m.Handle.ValueString()
	}
	if !m.Activeregions.IsNull() && !m.Activeregions.IsUnknown() {
		var items []string
		diags.Append(m.Activeregions.ElementsAs(ctx, &items, false)...)
		out["activeregions"] = items
	}
	if !m.Memorymb.IsNull() && !m.Memorymb.IsUnknown() {
		out["memorymb"] = m.Memorymb.ValueInt64()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out["name"] = m.Name.ValueString()
	}
	if !m.Maxconnections.IsNull() && !m.Maxconnections.IsUnknown() {
		out["maxconnections"] = m.Maxconnections.ValueInt64()
	}
	if !m.Maxitemsizemb.IsNull() && !m.Maxitemsizemb.IsUnknown() {
		out["maxitemsizemb"] = m.Maxitemsizemb.ValueInt64()
	}
	if !m.Nodes.IsNull() && !m.Nodes.IsUnknown() {
		out["nodes"] = m.Nodes.ValueInt64()
	}
	if !m.Project.IsNull() && !m.Project.IsUnknown() {
		out["project"] = m.Project.ValueString()
	}
	if !m.Threads.IsNull() && !m.Threads.IsUnknown() {
		out["threads"] = m.Threads.ValueInt64()
	}
	return out, diags
}

func apiToMemcachedModel(raw map[string]any) memcachedModel {
	m := memcachedModel{}
	if v, ok := raw["id"].(string); ok {
		m.ID = types.StringValue(v)
	} else {
		m.ID = types.StringNull()
	}
	if v, ok := raw["handle"].(string); ok {
		m.Handle = types.StringValue(v)
	} else {
		m.Handle = types.StringNull()
	}
	if items, ok := raw["activeregions"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if s, ok := it.(string); ok {
				elements = append(elements, types.StringValue(s))
			}
		}
		listVal, _ := types.ListValue(types.StringType, elements)
		m.Activeregions = listVal
	} else {
		m.Activeregions = types.ListNull(types.StringType)
	}
	if v, ok := raw["memorymb"].(float64); ok {
		m.Memorymb = types.Int64Value(int64(v))
	} else {
		m.Memorymb = types.Int64Null()
	}
	if v, ok := raw["name"].(string); ok {
		m.Name = types.StringValue(v)
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := raw["maxconnections"].(float64); ok {
		m.Maxconnections = types.Int64Value(int64(v))
	} else {
		m.Maxconnections = types.Int64Null()
	}
	if v, ok := raw["maxitemsizemb"].(float64); ok {
		m.Maxitemsizemb = types.Int64Value(int64(v))
	} else {
		m.Maxitemsizemb = types.Int64Null()
	}
	if v, ok := raw["nodes"].(float64); ok {
		m.Nodes = types.Int64Value(int64(v))
	} else {
		m.Nodes = types.Int64Null()
	}
	if v, ok := raw["project"].(string); ok {
		m.Project = types.StringValue(v)
	} else {
		m.Project = types.StringNull()
	}
	if v, ok := raw["threads"].(float64); ok {
		m.Threads = types.Int64Value(int64(v))
	} else {
		m.Threads = types.Int64Null()
	}
	if v, ok := raw["managedbycontainer"].(string); ok {
		m.Managedbycontainer = types.StringValue(v)
	} else {
		m.Managedbycontainer = types.StringNull()
	}
	if v, ok := raw["organisation"].(string); ok {
		m.Organisation = types.StringValue(v)
	} else {
		m.Organisation = types.StringNull()
	}
	if v, ok := raw["projectname"].(string); ok {
		m.Projectname = types.StringValue(v)
	} else {
		m.Projectname = types.StringNull()
	}
	if v, ok := raw["status"].(string); ok {
		m.Status = types.StringValue(v)
	} else {
		m.Status = types.StringNull()
	}
	return m
}

func memcachedModelsEqual(a, b memcachedModel) bool {
	if !a.Handle.Equal(b.Handle) {
		return false
	}
	if !a.Activeregions.Equal(b.Activeregions) {
		return false
	}
	if !a.Memorymb.Equal(b.Memorymb) {
		return false
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	if !a.Maxconnections.Equal(b.Maxconnections) {
		return false
	}
	if !a.Maxitemsizemb.Equal(b.Maxitemsizemb) {
		return false
	}
	if !a.Nodes.Equal(b.Nodes) {
		return false
	}
	if !a.Project.Equal(b.Project) {
		return false
	}
	if !a.Threads.Equal(b.Threads) {
		return false
	}
	return true
}
