// Code generated by cmd/generator. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"

	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/client"
)

var (
	_ resource.Resource                = &network_policyResource{}
	_ resource.ResourceWithConfigure   = &network_policyResource{}
	_ resource.ResourceWithImportState = &network_policyResource{}
)

func NewNetworkPolicyResource() resource.Resource {
	return &network_policyResource{}
}

type network_policyResource struct {
	client *client.Client
}

type network_policyModel struct {
	ID                    types.String `tfsdk:"id"`
	Handle                types.String `tfsdk:"handle"`
	Name                  types.String `tfsdk:"name"`
	Egresscidrs           types.List   `tfsdk:"egresscidrs"`
	Egressfqdns           types.List   `tfsdk:"egressfqdns"`
	Ingresspeers          types.List   `tfsdk:"ingresspeers"`
	L7enabled             types.Bool   `tfsdk:"l7enabled"`
	Ports                 types.List   `tfsdk:"ports"`
	Billable              types.Bool   `tfsdk:"billable"`
	Managedbyresourceid   types.String `tfsdk:"managedbyresourceid"`
	Managedbyresourcetype types.String `tfsdk:"managedbyresourcetype"`
	Organisation          types.String `tfsdk:"organisation"`
}

type network_policyPortsModel struct {
	Port     types.Int64  `tfsdk:"port"`
	Protocol types.String `tfsdk:"protocol"`
}

func (r *network_policyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_policy"
}

func (r *network_policyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Bahriya network_policy.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"handle": schema.StringAttribute{
				Required:    true,
				Description: "DNS-1123 compliant: lowercase alphanumeric and hyphens only.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"egresscidrs": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Description: "CIDR ranges this policy's targets are allowed to send outbound traffic to.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"egressfqdns": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Description: "Domain names allowed for outbound traffic. Coming soon — stored and validated now, enforced in a future release.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"ingresspeers": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Description: "Same-organisation project handles allowed to reach this policy's targets.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"l7enabled": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Enable L7 controls for this policy. Opts the policy into the application-layer engine and its per-replica charge for every container it is applied to. Automatically enabled when egress domains are set.",
			},
			"ports": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"port": schema.Int64Attribute{
							Required: true,
						},
						"protocol": schema.StringAttribute{
							Optional: true,
						},
					},
				},
				Optional:    true,
				Computed:    true,
				Description: "Optional port/protocol scoping applied to the rules above. Omit to allow all ports.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"billable": schema.BoolAttribute{
				Computed: true,
			},
			"managedbyresourceid": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourcetype": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organisation": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *network_policyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *network_policyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan network_policyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	handle := plan.Handle.ValueString()
	exists, err := r.client.HandleExists(ctx, "network_policy", handle)
	if err != nil {
		resp.Diagnostics.AddError("Handle existence check failed", err.Error())
		return
	}
	if exists {
		resp.Diagnostics.AddError(
			"Handle already in use",
			fmt.Sprintf("A network_policy with handle %q already exists in this organisation. Handles cannot be reused.", handle),
		)
		return
	}

	body, diags := planToNetworkPolicyPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPost, fmt.Sprintf("/organisations/%s/network_policies", r.client.OrganisationID()), body)
	if err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status from Create", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	var id string
	if err := json.Unmarshal(data, &id); err != nil {
		resp.Diagnostics.AddError("Decode created id failed", err.Error())
		return
	}

	state, diags := r.fetch(ctx, id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *network_policyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state network_policyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	if diags.HasError() {
		if diagsContainNotFound(diags) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.Append(diags...)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *network_policyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state network_policyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if network_policyModelsEqual(plan, state) {
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	}

	body, diags := planToNetworkPolicyPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPut, fmt.Sprintf("/organisations/%s/network_policies/%s", r.client.OrganisationID(), state.ID.ValueString()), body)
	if err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	if status != http.StatusOK {
		// Surface the API's message body (e.g. a 409 explaining a network policy is
		// already project-attached) so the user can act on it, not just the code.
		resp.Diagnostics.AddError("Unexpected status from Update", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *network_policyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state network_policyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, status, err := r.client.Do(ctx, http.MethodDelete, fmt.Sprintf("/organisations/%s/network_policies/%s", r.client.OrganisationID(), state.ID.ValueString()), nil)
	if err != nil && status != http.StatusNotFound {
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

func (r *network_policyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("id"), req.ID)...)
}

func (r *network_policyResource) fetch(ctx context.Context, id string) (network_policyModel, diagnostics) {
	var diags diagnostics
	data, status, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/network_policies/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		if status == http.StatusNotFound {
			diags.AddError("not_found", "resource was deleted out-of-band")
			return network_policyModel{}, diags
		}
		diags.AddError("Fetch failed", err.Error())
		return network_policyModel{}, diags
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		diags.AddError("Decode fetch response failed", err.Error())
		return network_policyModel{}, diags
	}
	return apiToNetworkPolicyModel(raw), diags
}

func planToNetworkPolicyPayload(ctx context.Context, m *network_policyModel) (map[string]any, diagnostics) {
	var diags diagnostics
	out := map[string]any{}
	if !m.Handle.IsNull() && !m.Handle.IsUnknown() {
		out["handle"] = m.Handle.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out["name"] = m.Name.ValueString()
	}
	if !m.Egresscidrs.IsNull() && !m.Egresscidrs.IsUnknown() {
		var items []string
		diags.Append(m.Egresscidrs.ElementsAs(ctx, &items, false)...)
		out["egresscidrs"] = items
	} else {
		out["egresscidrs"] = []string{}
	}
	if !m.Egressfqdns.IsNull() && !m.Egressfqdns.IsUnknown() {
		var items []string
		diags.Append(m.Egressfqdns.ElementsAs(ctx, &items, false)...)
		out["egressfqdns"] = items
	} else {
		out["egressfqdns"] = []string{}
	}
	if !m.Ingresspeers.IsNull() && !m.Ingresspeers.IsUnknown() {
		var items []string
		diags.Append(m.Ingresspeers.ElementsAs(ctx, &items, false)...)
		out["ingresspeers"] = items
	} else {
		out["ingresspeers"] = []string{}
	}
	if !m.L7enabled.IsNull() && !m.L7enabled.IsUnknown() {
		out["l7enabled"] = m.L7enabled.ValueBool()
	} else {
		out["l7enabled"] = false
	}
	if !m.Ports.IsNull() && !m.Ports.IsUnknown() {
		var nested []network_policyPortsModel
		diags.Append(m.Ports.ElementsAs(ctx, &nested, false)...)
		items := make([]map[string]any, 0, len(nested))
		for _, n := range nested {
			item := map[string]any{}
			if !n.Port.IsNull() && !n.Port.IsUnknown() {
				item["port"] = n.Port.ValueInt64()
			}
			if !n.Protocol.IsNull() && !n.Protocol.IsUnknown() {
				item["protocol"] = n.Protocol.ValueString()
			}
			items = append(items, item)
		}
		out["ports"] = items
	} else {
		out["ports"] = []map[string]any{}
	}
	return out, diags
}

func apiToNetworkPolicyModel(raw map[string]any) network_policyModel {
	m := network_policyModel{}
	if v, ok := raw["id"].(string); ok {
		m.ID = types.StringValue(v)
	} else {
		m.ID = types.StringNull()
	}
	if v, ok := raw["handle"].(string); ok {
		m.Handle = types.StringValue(v)
	} else {
		m.Handle = types.StringNull()
	}
	if v, ok := raw["name"].(string); ok {
		m.Name = types.StringValue(v)
	} else {
		m.Name = types.StringNull()
	}
	if items, ok := raw["egresscidrs"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if s, ok := it.(string); ok {
				elements = append(elements, types.StringValue(s))
			}
		}
		listVal, _ := types.ListValue(types.StringType, elements)
		m.Egresscidrs = listVal
	} else {
		m.Egresscidrs = types.ListNull(types.StringType)
	}
	if items, ok := raw["egressfqdns"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if s, ok := it.(string); ok {
				elements = append(elements, types.StringValue(s))
			}
		}
		listVal, _ := types.ListValue(types.StringType, elements)
		m.Egressfqdns = listVal
	} else {
		m.Egressfqdns = types.ListNull(types.StringType)
	}
	if items, ok := raw["ingresspeers"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if s, ok := it.(string); ok {
				elements = append(elements, types.StringValue(s))
			}
		}
		listVal, _ := types.ListValue(types.StringType, elements)
		m.Ingresspeers = listVal
	} else {
		m.Ingresspeers = types.ListNull(types.StringType)
	}
	if v, ok := raw["l7enabled"].(bool); ok {
		m.L7enabled = types.BoolValue(v)
	} else {
		m.L7enabled = types.BoolNull()
	}
	if items, ok := raw["ports"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if obj, ok := it.(map[string]any); ok {
				attrVals := map[string]attr.Value{}
				if v, ok := obj["port"].(float64); ok {
					attrVals["port"] = types.Int64Value(int64(v))
				} else {
					attrVals["port"] = types.Int64Null()
				}
				if v, ok := obj["protocol"].(string); ok {
					attrVals["protocol"] = types.StringValue(v)
				} else {
					attrVals["protocol"] = types.StringNull()
				}
				objVal, _ := types.ObjectValue(network_policyPortsAttrTypes(), attrVals)
				elements = append(elements, objVal)
			}
		}
		listVal, _ := types.ListValue(network_policyPortsObjectType(), elements)
		m.Ports = listVal
	} else {
		m.Ports = types.ListNull(network_policyPortsObjectType())
	}
	if v, ok := raw["billable"].(bool); ok {
		m.Billable = types.BoolValue(v)
	} else {
		m.Billable = types.BoolNull()
	}
	if v, ok := raw["managedbyresourceid"].(string); ok {
		m.Managedbyresourceid = types.StringValue(v)
	} else {
		m.Managedbyresourceid = types.StringNull()
	}
	if v, ok := raw["managedbyresourcetype"].(string); ok {
		m.Managedbyresourcetype = types.StringValue(v)
	} else {
		m.Managedbyresourcetype = types.StringNull()
	}
	if v, ok := raw["organisation"].(string); ok {
		m.Organisation = types.StringValue(v)
	} else {
		m.Organisation = types.StringNull()
	}
	return m
}

func network_policyPortsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"port":     types.Int64Type,
		"protocol": types.StringType,
	}
}

func network_policyPortsObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: network_policyPortsAttrTypes()}
}

func network_policyModelsEqual(a, b network_policyModel) bool {
	if !a.Handle.Equal(b.Handle) {
		return false
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	if !a.Egresscidrs.Equal(b.Egresscidrs) {
		return false
	}
	if !a.Egressfqdns.Equal(b.Egressfqdns) {
		return false
	}
	if !a.Ingresspeers.Equal(b.Ingresspeers) {
		return false
	}
	if !a.L7enabled.Equal(b.L7enabled) {
		return false
	}
	if !a.Ports.Equal(b.Ports) {
		return false
	}
	return true
}
