// Code generated by cmd/generator. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"

	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/client"
)

var (
	_ resource.Resource                = &projectResource{}
	_ resource.ResourceWithConfigure   = &projectResource{}
	_ resource.ResourceWithImportState = &projectResource{}
)

func NewProjectResource() resource.Resource {
	return &projectResource{}
}

type projectResource struct {
	client *client.Client
}

type projectModel struct {
	ID                 types.String `tfsdk:"id"`
	Handle             types.String `tfsdk:"handle"`
	Name               types.String `tfsdk:"name"`
	Regions            types.List   `tfsdk:"regions"`
	Users              types.List   `tfsdk:"users"`
	Organisation       types.String `tfsdk:"organisation"`
	Quotalimitcpu      types.String `tfsdk:"quotalimitcpu"`
	Quotalimitmemory   types.String `tfsdk:"quotalimitmemory"`
	Quotarequestcpu    types.String `tfsdk:"quotarequestcpu"`
	Quotarequestmemory types.String `tfsdk:"quotarequestmemory"`
}

func (r *projectResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project"
}

func (r *projectResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Bahriya project.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"handle": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"regions": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
				Description: "Regions this project may deploy into. At least one is required.",
			},
			"users": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"organisation": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"quotalimitcpu": schema.StringAttribute{
				Computed:    true,
				Description: "Namespace CPU limit quota. Null = platform default.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"quotalimitmemory": schema.StringAttribute{
				Computed:    true,
				Description: "Namespace memory limit quota. Null = platform default.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"quotarequestcpu": schema.StringAttribute{
				Computed:    true,
				Description: "Namespace CPU request quota. Null = platform default.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"quotarequestmemory": schema.StringAttribute{
				Computed:    true,
				Description: "Namespace memory request quota. Null = platform default.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *projectResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *projectResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan projectModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	handle := plan.Handle.ValueString()
	exists, err := r.client.HandleExists(ctx, "project", handle)
	if err != nil {
		resp.Diagnostics.AddError("Handle existence check failed", err.Error())
		return
	}
	if exists {
		resp.Diagnostics.AddError(
			"Handle already in use",
			fmt.Sprintf("A project with handle %q already exists in this organisation. Handles cannot be reused.", handle),
		)
		return
	}

	body, diags := planToProjectPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPost, fmt.Sprintf("/organisations/%s/projects", r.client.OrganisationID()), body)
	if err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	if status == http.StatusConflict {
		// A refusal on project resource limits is the one 409 with a structured body, and it is
		// the one a practitioner can act on: it says which ceiling, in which region, and by how
		// much. Rendering it as raw JSON next to "Unexpected status" would bury that.
		if verdict := client.DecodeQuotaRefusal(data); verdict != nil {
			resp.Diagnostics.AddError("Project resource limits exceeded", client.QuotaDetail(verdict))
			return
		}
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status from Create", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	id, verdict, err := client.DecodeWrite(data)
	if err != nil {
		resp.Diagnostics.AddError("Decode created id failed", err.Error())
		return
	}
	if warning := client.QuotaWarning(verdict); warning != "" {
		// Applied, and running. It may still be unable to reach the replica count the
		// configuration asks for, which nothing else in the plan or state would ever reveal.
		resp.Diagnostics.AddWarning("Scaling limited by project resource limits", warning)
	}

	state, diags := r.fetch(ctx, id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *projectResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state projectModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	if diags.HasError() {
		if diagsContainNotFound(diags) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.Append(diags...)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *projectResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state projectModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if projectModelsEqual(plan, state) {
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	}

	body, diags := planToProjectPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPut, fmt.Sprintf("/organisations/%s/projects/%s", r.client.OrganisationID(), state.ID.ValueString()), body)
	if err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	if status != http.StatusOK {
		// Surface the API's message body (e.g. a 409 explaining a network policy is
		// already project-attached) so the user can act on it, not just the code.
		resp.Diagnostics.AddError("Unexpected status from Update", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *projectResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state projectModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteBody := map[string]any{"confirmName": state.Name.ValueString()}
	_, status, err := r.client.Do(ctx, http.MethodDelete, fmt.Sprintf("/organisations/%s/projects/%s", r.client.OrganisationID(), state.ID.ValueString()), deleteBody)
	if err != nil && status != http.StatusNotFound {
		if status == http.StatusConflict {
			resp.Diagnostics.AddError(
				"Delete blocked by active dependencies",
				err.Error()+"\n\n"+"Hint: a project can only be deleted once every container, memcached, registry, and secret it owns is gone. For containers and memcached this means status 'terminated' — instances stuck in 'error', 'terminating', 'provisioning', 'running', or 'suspended' all count as active. Containers reach 'error' when the deploy rolled back and they do not self-recover; investigate via the admin console and explicitly terminate them. Registries and secrets must be detached from the project before delete.",
			)
			return
		}
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

func (r *projectResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("id"), req.ID)...)
}

func (r *projectResource) fetch(ctx context.Context, id string) (projectModel, diagnostics) {
	var diags diagnostics
	data, status, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/projects/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		if status == http.StatusNotFound {
			diags.AddError("not_found", "resource was deleted out-of-band")
			return projectModel{}, diags
		}
		diags.AddError("Fetch failed", err.Error())
		return projectModel{}, diags
	}
	var envelope map[string]any
	if err := json.Unmarshal(data, &envelope); err != nil {
		diags.AddError("Decode fetch response failed", err.Error())
		return projectModel{}, diags
	}
	items, ok := envelope["projects"].([]any)
	if !ok || len(items) == 0 {
		diags.AddError("not_found", "resource was deleted out-of-band")
		return projectModel{}, diags
	}
	raw, ok := items[0].(map[string]any)
	if !ok {
		diags.AddError("Decode fetch response failed", "unexpected item shape")
		return projectModel{}, diags
	}
	return apiToProjectModel(raw), diags
}

func planToProjectPayload(ctx context.Context, m *projectModel) (map[string]any, diagnostics) {
	var diags diagnostics
	out := map[string]any{}
	if !m.Handle.IsNull() && !m.Handle.IsUnknown() {
		out["handle"] = m.Handle.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out["name"] = m.Name.ValueString()
	}
	if !m.Regions.IsNull() && !m.Regions.IsUnknown() {
		var items []string
		diags.Append(m.Regions.ElementsAs(ctx, &items, false)...)
		out["regions"] = items
	}
	if !m.Users.IsNull() && !m.Users.IsUnknown() {
		var items []string
		diags.Append(m.Users.ElementsAs(ctx, &items, false)...)
		out["users"] = items
	} else {
		out["users"] = []string{}
	}
	return out, diags
}

func apiToProjectModel(raw map[string]any) projectModel {
	m := projectModel{}
	if v, ok := raw["id"].(string); ok {
		m.ID = types.StringValue(v)
	} else {
		m.ID = types.StringNull()
	}
	if v, ok := raw["handle"].(string); ok {
		m.Handle = types.StringValue(v)
	} else {
		m.Handle = types.StringNull()
	}
	if v, ok := raw["name"].(string); ok {
		m.Name = types.StringValue(v)
	} else {
		m.Name = types.StringNull()
	}
	if items, ok := raw["regions"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if s, ok := it.(string); ok {
				elements = append(elements, types.StringValue(s))
			}
		}
		listVal, _ := types.ListValue(types.StringType, elements)
		m.Regions = listVal
	} else {
		m.Regions = types.ListNull(types.StringType)
	}
	if items, ok := raw["users"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if s, ok := it.(string); ok {
				elements = append(elements, types.StringValue(s))
			}
		}
		listVal, _ := types.ListValue(types.StringType, elements)
		m.Users = listVal
	} else {
		m.Users = types.ListNull(types.StringType)
	}
	if v, ok := raw["organisation"].(string); ok {
		m.Organisation = types.StringValue(v)
	} else {
		m.Organisation = types.StringNull()
	}
	if v, ok := raw["quotalimitcpu"].(string); ok {
		m.Quotalimitcpu = types.StringValue(v)
	} else {
		m.Quotalimitcpu = types.StringNull()
	}
	if v, ok := raw["quotalimitmemory"].(string); ok {
		m.Quotalimitmemory = types.StringValue(v)
	} else {
		m.Quotalimitmemory = types.StringNull()
	}
	if v, ok := raw["quotarequestcpu"].(string); ok {
		m.Quotarequestcpu = types.StringValue(v)
	} else {
		m.Quotarequestcpu = types.StringNull()
	}
	if v, ok := raw["quotarequestmemory"].(string); ok {
		m.Quotarequestmemory = types.StringValue(v)
	} else {
		m.Quotarequestmemory = types.StringNull()
	}
	return m
}

func projectModelsEqual(a, b projectModel) bool {
	if !a.Handle.Equal(b.Handle) {
		return false
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	if !a.Regions.Equal(b.Regions) {
		return false
	}
	if !a.Users.Equal(b.Users) {
		return false
	}
	return true
}
