// Code generated by cmd/generator. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/client"
)

var (
	_ resource.Resource                = &projectEnvFileAttachmentResource{}
	_ resource.ResourceWithConfigure   = &projectEnvFileAttachmentResource{}
	_ resource.ResourceWithImportState = &projectEnvFileAttachmentResource{}
)

func NewProjectEnvFileAttachmentResource() resource.Resource {
	return &projectEnvFileAttachmentResource{}
}

type projectEnvFileAttachmentResource struct {
	client *client.Client
}

type projectEnvFileAttachmentModel struct {
	ID        types.String `tfsdk:"id"`
	ProjectID types.String `tfsdk:"project_id"`
	Handle    types.String `tfsdk:"handle"`
	JoinID    types.String `tfsdk:"join_id"`
}

func (r *projectEnvFileAttachmentResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_env_file_attachment"
}

func (r *projectEnvFileAttachmentResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Attaches a env_file to a Bahriya project. Both project_id and handle force replacement.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Composite identifier of the attachment ({project_id}:{handle}).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_id": schema.StringAttribute{
				Required:    true,
				Description: "ID (UUID) of the project the env_file is attached to.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"handle": schema.StringAttribute{
				Required:    true,
				Description: "Handle of the env_file to attach.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"join_id": schema.StringAttribute{
				Computed:    true,
				Description: "Identifier of the underlying project-attachment join row.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *projectEnvFileAttachmentResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = c
}

func (r *projectEnvFileAttachmentResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan projectEnvFileAttachmentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectID := plan.ProjectID.ValueString()
	handle := plan.Handle.ValueString()

	data, status, err := r.client.Do(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/organisations/%s/projects/%s/attach/env_files/%s", r.client.OrganisationID(), projectID, handle),
		nil,
	)
	if err != nil {
		resp.Diagnostics.AddError("Attach failed", err.Error())
		return
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status from attach", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	var joinID string
	if err := json.Unmarshal(data, &joinID); err != nil {
		resp.Diagnostics.AddError("Decode join id failed", err.Error())
		return
	}

	plan.JoinID = types.StringValue(joinID)
	plan.ID = types.StringValue(projectID + ":" + handle)
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *projectEnvFileAttachmentResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state projectEnvFileAttachmentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectID := state.ProjectID.ValueString()
	handle := state.Handle.ValueString()

	data, status, err := r.client.Do(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/organisations/%s/projects/%s/attachments", r.client.OrganisationID(), projectID),
		nil,
	)
	if err != nil {
		if status == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("List attachments failed", err.Error())
		return
	}

	var envelope map[string]any
	if err := json.Unmarshal(data, &envelope); err != nil {
		resp.Diagnostics.AddError("Decode attachments failed", err.Error())
		return
	}

	items, _ := envelope["envfiles"].([]any)
	for _, it := range items {
		obj, ok := it.(map[string]any)
		if !ok {
			continue
		}
		if h, _ := obj["handle"].(string); h == handle {
			state.ID = types.StringValue(projectID + ":" + handle)
			resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
			return
		}
	}

	resp.State.RemoveResource(ctx)
}

func (r *projectEnvFileAttachmentResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Both project_id and handle force replacement — nothing to update.
	var plan projectEnvFileAttachmentModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *projectEnvFileAttachmentResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state projectEnvFileAttachmentModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	projectID := state.ProjectID.ValueString()
	handle := state.Handle.ValueString()

	_, status, err := r.client.Do(
		ctx,
		http.MethodDelete,
		fmt.Sprintf("/organisations/%s/projects/%s/attach/env_files/%s", r.client.OrganisationID(), projectID, handle),
		nil,
	)
	if err != nil && status != http.StatusNotFound {
		resp.Diagnostics.AddError("Detach failed", err.Error())
		return
	}
}

func (r *projectEnvFileAttachmentResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			"Expected import id in the form `{project_id}:{handle}` (e.g. `8a3d...:my-cert`).",
		)
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("project_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("handle"), parts[1])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("id"), req.ID)...)
}
