// Code generated by cmd/generator. DO NOT EDIT.

package resources

import "github.com/hashicorp/terraform-plugin-framework/resource"

// All returns the set of resource constructors for the Bahriya provider.
// Append to this slice as new resources are generated.
func All() []func() resource.Resource {
	return []func() resource.Resource{
		NewProjectResource,
		NewRegistryResource,
		NewSecretResource,
		NewMemcachedResource,
		NewContainerResource,
	}
}
