// Code generated by cmd/generator. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"

	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/client"
)

var (
	_ resource.Resource                = &registryResource{}
	_ resource.ResourceWithConfigure   = &registryResource{}
	_ resource.ResourceWithImportState = &registryResource{}
)

func NewRegistryResource() resource.Resource {
	return &registryResource{}
}

type registryResource struct {
	client *client.Client
}

type registryModel struct {
	ID                    types.String `tfsdk:"id"`
	Handle                types.String `tfsdk:"handle"`
	Name                  types.String `tfsdk:"name"`
	Password              types.String `tfsdk:"password"`
	Server                types.String `tfsdk:"server"`
	Username              types.String `tfsdk:"username"`
	Maxversions           types.Int64  `tfsdk:"maxversions"`
	Billable              types.Bool   `tfsdk:"billable"`
	Currentversionid      types.String `tfsdk:"currentversionid"`
	Managedbyresourceid   types.String `tfsdk:"managedbyresourceid"`
	Managedbyresourcetype types.String `tfsdk:"managedbyresourcetype"`
}

func (r *registryResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_registry"
}

func (r *registryResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Bahriya registry.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"handle": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"password": schema.StringAttribute{
				Required:  true,
				Sensitive: true,
			},
			"server": schema.StringAttribute{
				Required: true,
			},
			"username": schema.StringAttribute{
				Required: true,
			},
			"maxversions": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"billable": schema.BoolAttribute{
				Computed: true,
			},
			"currentversionid": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourceid": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourcetype": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *registryResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *registryResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan registryModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	handle := plan.Handle.ValueString()
	exists, err := r.client.HandleExists(ctx, "registry", handle)
	if err != nil {
		resp.Diagnostics.AddError("Handle existence check failed", err.Error())
		return
	}
	if exists {
		resp.Diagnostics.AddError(
			"Handle already in use",
			fmt.Sprintf("A registry with handle %q already exists in this organisation. Handles cannot be reused.", handle),
		)
		return
	}

	body, diags := planToRegistryPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	data, status, err := r.client.Do(ctx, http.MethodPost, fmt.Sprintf("/organisations/%s/registries", r.client.OrganisationID()), body)
	if err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status from Create", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	var id string
	if err := json.Unmarshal(data, &id); err != nil {
		resp.Diagnostics.AddError("Decode created id failed", err.Error())
		return
	}

	state, diags := r.fetch(ctx, id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	state.Password = knownValue(plan.Password, types.StringNull())

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *registryResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state registryModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	if diags.HasError() {
		if diagsContainNotFound(diags) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.Append(diags...)
		return
	}
	fresh.Password = state.Password

	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *registryResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state registryModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if registryModelsEqual(plan, state) {
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	}

	body, diags := planToRegistryPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	data, status, err := r.client.Do(ctx, http.MethodPut, fmt.Sprintf("/organisations/%s/registries/%s", r.client.OrganisationID(), state.ID.ValueString()), body)
	if err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	if status != http.StatusOK {
		// Surface the API's message body (e.g. a 409 explaining a network policy is
		// already project-attached) so the user can act on it, not just the code.
		resp.Diagnostics.AddError("Unexpected status from Update", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	fresh.Password = knownValue(plan.Password, state.Password)
	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *registryResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state registryModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, status, err := r.client.Do(ctx, http.MethodDelete, fmt.Sprintf("/organisations/%s/registries/%s", r.client.OrganisationID(), state.ID.ValueString()), nil)
	if err != nil && status != http.StatusNotFound {
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

func (r *registryResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("id"), req.ID)...)
}

func (r *registryResource) fetch(ctx context.Context, id string) (registryModel, diagnostics) {
	var diags diagnostics
	data, status, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/registries/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		if status == http.StatusNotFound {
			diags.AddError("not_found", "resource was deleted out-of-band")
			return registryModel{}, diags
		}
		diags.AddError("Fetch failed", err.Error())
		return registryModel{}, diags
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		diags.AddError("Decode fetch response failed", err.Error())
		return registryModel{}, diags
	}
	return apiToRegistryModel(raw), diags
}

func planToRegistryPayload(ctx context.Context, m *registryModel) (map[string]any, diagnostics) {
	var diags diagnostics
	out := map[string]any{}
	if !m.Handle.IsNull() && !m.Handle.IsUnknown() {
		out["handle"] = m.Handle.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out["name"] = m.Name.ValueString()
	}
	if !m.Password.IsNull() && !m.Password.IsUnknown() {
		out["password"] = m.Password.ValueString()
	}
	if !m.Server.IsNull() && !m.Server.IsUnknown() {
		out["server"] = m.Server.ValueString()
	}
	if !m.Username.IsNull() && !m.Username.IsUnknown() {
		out["username"] = m.Username.ValueString()
	}
	if !m.Maxversions.IsNull() && !m.Maxversions.IsUnknown() {
		out["maxversions"] = m.Maxversions.ValueInt64()
	}
	return out, diags
}

func apiToRegistryModel(raw map[string]any) registryModel {
	m := registryModel{}
	if v, ok := raw["id"].(string); ok {
		m.ID = types.StringValue(v)
	} else {
		m.ID = types.StringNull()
	}
	if v, ok := raw["handle"].(string); ok {
		m.Handle = types.StringValue(v)
	} else {
		m.Handle = types.StringNull()
	}
	if v, ok := raw["name"].(string); ok {
		m.Name = types.StringValue(v)
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := raw["password"].(string); ok {
		m.Password = types.StringValue(v)
	} else {
		m.Password = types.StringNull()
	}
	if v, ok := raw["server"].(string); ok {
		m.Server = types.StringValue(v)
	} else {
		m.Server = types.StringNull()
	}
	if v, ok := raw["username"].(string); ok {
		m.Username = types.StringValue(v)
	} else {
		m.Username = types.StringNull()
	}
	if v, ok := raw["maxversions"].(float64); ok {
		m.Maxversions = types.Int64Value(int64(v))
	} else {
		m.Maxversions = types.Int64Null()
	}
	if v, ok := raw["billable"].(bool); ok {
		m.Billable = types.BoolValue(v)
	} else {
		m.Billable = types.BoolNull()
	}
	if v, ok := raw["currentversionid"].(string); ok {
		m.Currentversionid = types.StringValue(v)
	} else {
		m.Currentversionid = types.StringNull()
	}
	if v, ok := raw["managedbyresourceid"].(string); ok {
		m.Managedbyresourceid = types.StringValue(v)
	} else {
		m.Managedbyresourceid = types.StringNull()
	}
	if v, ok := raw["managedbyresourcetype"].(string); ok {
		m.Managedbyresourcetype = types.StringValue(v)
	} else {
		m.Managedbyresourcetype = types.StringNull()
	}
	return m
}

func registryModelsEqual(a, b registryModel) bool {
	if !a.Handle.Equal(b.Handle) {
		return false
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	if !a.Password.Equal(b.Password) {
		return false
	}
	if !a.Server.Equal(b.Server) {
		return false
	}
	if !a.Username.Equal(b.Username) {
		return false
	}
	if !a.Maxversions.Equal(b.Maxversions) {
		return false
	}
	return true
}
