// Code generated by cmd/generator. DO NOT EDIT.

package resources

import "github.com/hashicorp/terraform-plugin-framework/resource"

// All returns the set of resource constructors for the Bahriya provider.
// Append to this slice as new resources are generated.
func All() []func() resource.Resource {
	return []func() resource.Resource{
		NewProjectResource,
		NewRegistryResource,
		NewSecretResource,
		NewMemcachedResource,
		NewValkeyResource,
		NewContainerResource,
		NewTLSBundleResource,
		NewX509CertResource,
		NewGpgKeypairResource,
		NewSSHKeypairResource,
		NewEncryptionKeyResource,
		NewEnvFileResource,
		NewYAMLConfigResource,
		NewJSONConfigResource,
		NewPlainConfigResource,
		NewNetworkPolicyResource,
		NewProjectRegistryAttachmentResource,
		NewProjectSecretAttachmentResource,
		NewProjectTLSBundleAttachmentResource,
		NewProjectX509CertAttachmentResource,
		NewProjectGpgKeypairAttachmentResource,
		NewProjectSSHKeypairAttachmentResource,
		NewProjectEncryptionKeyAttachmentResource,
		NewProjectEnvFileAttachmentResource,
		NewProjectYAMLConfigAttachmentResource,
		NewProjectJSONConfigAttachmentResource,
		NewProjectPlainConfigAttachmentResource,
		NewProjectNetworkPolicyAttachmentResource,
		// Hand-written resources — preserved via handWrittenResources in cmd/generator/main.go.
		NewPathRuleResource,
		NewRoleResource,
		NewResourceGrantResource,
		NewBillingDetailsResource,
	}
}
