// Code generated by cmd/generator. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"

	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/client"
)

var (
	_ resource.Resource                = &tls_bundleResource{}
	_ resource.ResourceWithConfigure   = &tls_bundleResource{}
	_ resource.ResourceWithImportState = &tls_bundleResource{}
)

func NewTLSBundleResource() resource.Resource {
	return &tls_bundleResource{}
}

type tls_bundleResource struct {
	client *client.Client
}

type tls_bundleModel struct {
	ID                    types.String `tfsdk:"id"`
	Handle                types.String `tfsdk:"handle"`
	Ca                    types.String `tfsdk:"ca"`
	Cert                  types.String `tfsdk:"cert"`
	Key                   types.String `tfsdk:"key"`
	Name                  types.String `tfsdk:"name"`
	Maxversions           types.Int64  `tfsdk:"maxversions"`
	Algorithm             types.String `tfsdk:"algorithm"`
	Billable              types.Bool   `tfsdk:"billable"`
	Currentversion        types.Int64  `tfsdk:"currentversion"`
	Fingerprint           types.String `tfsdk:"fingerprint"`
	Issuer                types.String `tfsdk:"issuer"`
	Keybits               types.Int64  `tfsdk:"keybits"`
	Managedbyresourceid   types.String `tfsdk:"managedbyresourceid"`
	Managedbyresourcetype types.String `tfsdk:"managedbyresourcetype"`
	Organisation          types.String `tfsdk:"organisation"`
	Subject               types.String `tfsdk:"subject"`
}

func (r *tls_bundleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tls_bundle"
}

func (r *tls_bundleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Bahriya tls_bundle.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"handle": schema.StringAttribute{
				Required:    true,
				Description: "DNS-1123 compliant: lowercase alphanumeric and hyphens only.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"ca": schema.StringAttribute{
				Required:    true,
				Description: "PEM-encoded CA certificate.",
			},
			"cert": schema.StringAttribute{
				Required:    true,
				Description: "PEM-encoded server certificate.",
			},
			"key": schema.StringAttribute{
				Required:    true,
				Sensitive:   true,
				Description: "PEM-encoded private key. Never returned on read.",
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"maxversions": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"algorithm": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"billable": schema.BoolAttribute{
				Computed: true,
			},
			"currentversion": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"fingerprint": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"issuer": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"keybits": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourceid": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourcetype": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organisation": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"subject": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *tls_bundleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *tls_bundleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan tls_bundleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	handle := plan.Handle.ValueString()
	exists, err := r.client.HandleExists(ctx, "tls_bundle", handle)
	if err != nil {
		resp.Diagnostics.AddError("Handle existence check failed", err.Error())
		return
	}
	if exists {
		resp.Diagnostics.AddError(
			"Handle already in use",
			fmt.Sprintf("A tls_bundle with handle %q already exists in this organisation. Handles cannot be reused.", handle),
		)
		return
	}

	body, diags := planToTLSBundlePayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPost, fmt.Sprintf("/organisations/%s/tls_bundles", r.client.OrganisationID()), body)
	if err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	if status == http.StatusConflict {
		// A refusal on project resource limits is the one 409 with a structured body, and it is
		// the one a practitioner can act on: it says which ceiling, in which region, and by how
		// much. Rendering it as raw JSON next to "Unexpected status" would bury that.
		if verdict := client.DecodeQuotaRefusal(data); verdict != nil {
			resp.Diagnostics.AddError("Project resource limits exceeded", client.QuotaDetail(verdict))
			return
		}
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status from Create", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	id, verdict, err := client.DecodeWrite(data)
	if err != nil {
		resp.Diagnostics.AddError("Decode created id failed", err.Error())
		return
	}
	if warning := client.QuotaWarning(verdict); warning != "" {
		// Applied, and running. It may still be unable to reach the replica count the
		// configuration asks for, which nothing else in the plan or state would ever reveal.
		resp.Diagnostics.AddWarning("Scaling limited by project resource limits", warning)
	}

	state, diags := r.fetch(ctx, id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	state.Key = knownValue(plan.Key, types.StringNull())

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *tls_bundleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state tls_bundleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	if diags.HasError() {
		if diagsContainNotFound(diags) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.Append(diags...)
		return
	}
	fresh.Key = state.Key

	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *tls_bundleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state tls_bundleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if tls_bundleModelsEqual(plan, state) {
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	}

	body, diags := planToTLSBundlePayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPut, fmt.Sprintf("/organisations/%s/tls_bundles/%s", r.client.OrganisationID(), state.ID.ValueString()), body)
	if err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	if status != http.StatusOK {
		// Surface the API's message body (e.g. a 409 explaining a network policy is
		// already project-attached) so the user can act on it, not just the code.
		resp.Diagnostics.AddError("Unexpected status from Update", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	fresh.Key = knownValue(plan.Key, state.Key)
	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *tls_bundleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state tls_bundleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, status, err := r.client.Do(ctx, http.MethodDelete, fmt.Sprintf("/organisations/%s/tls_bundles/%s", r.client.OrganisationID(), state.ID.ValueString()), nil)
	if err != nil && status != http.StatusNotFound {
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

func (r *tls_bundleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("id"), req.ID)...)
}

func (r *tls_bundleResource) fetch(ctx context.Context, id string) (tls_bundleModel, diagnostics) {
	var diags diagnostics
	data, status, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/tls_bundles/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		if status == http.StatusNotFound {
			diags.AddError("not_found", "resource was deleted out-of-band")
			return tls_bundleModel{}, diags
		}
		diags.AddError("Fetch failed", err.Error())
		return tls_bundleModel{}, diags
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		diags.AddError("Decode fetch response failed", err.Error())
		return tls_bundleModel{}, diags
	}
	return apiToTLSBundleModel(raw), diags
}

func planToTLSBundlePayload(ctx context.Context, m *tls_bundleModel) (map[string]any, diagnostics) {
	var diags diagnostics
	out := map[string]any{}
	if !m.Handle.IsNull() && !m.Handle.IsUnknown() {
		out["handle"] = m.Handle.ValueString()
	}
	if !m.Ca.IsNull() && !m.Ca.IsUnknown() {
		out["ca"] = m.Ca.ValueString()
	}
	if !m.Cert.IsNull() && !m.Cert.IsUnknown() {
		out["cert"] = m.Cert.ValueString()
	}
	if !m.Key.IsNull() && !m.Key.IsUnknown() {
		out["key"] = m.Key.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out["name"] = m.Name.ValueString()
	}
	if !m.Maxversions.IsNull() && !m.Maxversions.IsUnknown() {
		out["maxversions"] = m.Maxversions.ValueInt64()
	}
	return out, diags
}

func apiToTLSBundleModel(raw map[string]any) tls_bundleModel {
	m := tls_bundleModel{}
	if v, ok := raw["id"].(string); ok {
		m.ID = types.StringValue(v)
	} else {
		m.ID = types.StringNull()
	}
	if v, ok := raw["handle"].(string); ok {
		m.Handle = types.StringValue(v)
	} else {
		m.Handle = types.StringNull()
	}
	if v, ok := raw["ca"].(string); ok {
		m.Ca = types.StringValue(v)
	} else {
		m.Ca = types.StringNull()
	}
	if v, ok := raw["cert"].(string); ok {
		m.Cert = types.StringValue(v)
	} else {
		m.Cert = types.StringNull()
	}
	if v, ok := raw["key"].(string); ok {
		m.Key = types.StringValue(v)
	} else {
		m.Key = types.StringNull()
	}
	if v, ok := raw["name"].(string); ok {
		m.Name = types.StringValue(v)
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := raw["maxversions"].(float64); ok {
		m.Maxversions = types.Int64Value(int64(v))
	} else {
		m.Maxversions = types.Int64Null()
	}
	if v, ok := raw["algorithm"].(string); ok {
		m.Algorithm = types.StringValue(v)
	} else {
		m.Algorithm = types.StringNull()
	}
	if v, ok := raw["billable"].(bool); ok {
		m.Billable = types.BoolValue(v)
	} else {
		m.Billable = types.BoolNull()
	}
	if v, ok := raw["currentversion"].(float64); ok {
		m.Currentversion = types.Int64Value(int64(v))
	} else {
		m.Currentversion = types.Int64Null()
	}
	if v, ok := raw["fingerprint"].(string); ok {
		m.Fingerprint = types.StringValue(v)
	} else {
		m.Fingerprint = types.StringNull()
	}
	if v, ok := raw["issuer"].(string); ok {
		m.Issuer = types.StringValue(v)
	} else {
		m.Issuer = types.StringNull()
	}
	if v, ok := raw["keybits"].(float64); ok {
		m.Keybits = types.Int64Value(int64(v))
	} else {
		m.Keybits = types.Int64Null()
	}
	if v, ok := raw["managedbyresourceid"].(string); ok {
		m.Managedbyresourceid = types.StringValue(v)
	} else {
		m.Managedbyresourceid = types.StringNull()
	}
	if v, ok := raw["managedbyresourcetype"].(string); ok {
		m.Managedbyresourcetype = types.StringValue(v)
	} else {
		m.Managedbyresourcetype = types.StringNull()
	}
	if v, ok := raw["organisation"].(string); ok {
		m.Organisation = types.StringValue(v)
	} else {
		m.Organisation = types.StringNull()
	}
	if v, ok := raw["subject"].(string); ok {
		m.Subject = types.StringValue(v)
	} else {
		m.Subject = types.StringNull()
	}
	return m
}

func tls_bundleModelsEqual(a, b tls_bundleModel) bool {
	if !a.Handle.Equal(b.Handle) {
		return false
	}
	if !a.Ca.Equal(b.Ca) {
		return false
	}
	if !a.Cert.Equal(b.Cert) {
		return false
	}
	if !a.Key.Equal(b.Key) {
		return false
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	if !a.Maxversions.Equal(b.Maxversions) {
		return false
	}
	return true
}
