// Code generated by cmd/generator. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"
	"strconv"
	"time"

	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/client"
	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/lifecycle"
)

var (
	_ resource.Resource                = &valkeyResource{}
	_ resource.ResourceWithConfigure   = &valkeyResource{}
	_ resource.ResourceWithImportState = &valkeyResource{}
)

func NewValkeyResource() resource.Resource {
	return &valkeyResource{}
}

type valkeyResource struct {
	client *client.Client
}

type valkeyModel struct {
	ID              types.String `tfsdk:"id"`
	Handle          types.String `tfsdk:"handle"`
	Activeregions   types.List   `tfsdk:"activeregions"`
	Memorymb        types.Int64  `tfsdk:"memorymb"`
	Name            types.String `tfsdk:"name"`
	Purpose         types.String `tfsdk:"purpose"`
	Tier            types.String `tfsdk:"tier"`
	Allowedips      types.List   `tfsdk:"allowedips"`
	Authenabled     types.Bool   `tfsdk:"authenabled"`
	Backupenabled   types.Bool   `tfsdk:"backupenabled"`
	Backupschedule  types.String `tfsdk:"backupschedule"`
	Config          types.Map    `tfsdk:"config"`
	Defaulthostname types.String `tfsdk:"defaulthostname"`
	Externalenabled types.Bool   `tfsdk:"externalenabled"`
	Hostnames       types.List   `tfsdk:"hostnames"`
	Maxmemorypolicy types.String `tfsdk:"maxmemorypolicy"`
	Networkpolicies types.List   `tfsdk:"networkpolicies"`
	Password        types.String `tfsdk:"password"`
	Project         types.String `tfsdk:"project"`
	Shards          types.Int64  `tfsdk:"shards"`
	Size            types.String `tfsdk:"size"`
	Storagegb       types.Int64  `tfsdk:"storagegb"`
	Tlsbundle       types.String `tfsdk:"tlsbundle"`
	Tlsenabled      types.Bool   `tfsdk:"tlsenabled"`
	Nodes           types.Int64  `tfsdk:"nodes"`
	Organisation    types.String `tfsdk:"organisation"`
	Projectname     types.String `tfsdk:"projectname"`
	Status          types.String `tfsdk:"status"`
}

type valkeyHostnamesModel struct {
	Hostname types.String `tfsdk:"hostname"`
}

func (r *valkeyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_valkey"
}

func (r *valkeyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Bahriya valkey.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"handle": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"activeregions": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
				Description: "Regions this instance deploys into. At least one is required. Each region runs an independent copy with the same configuration and its own data.",
			},
			"memorymb": schema.Int64Attribute{
				Required:    true,
				Description: "Memory per node in MB. Billed per node.",
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"purpose": schema.StringAttribute{
				Required:    true,
				Description: "Sets the defaults bundle: cache = no persistence, allkeys-lru; store = RDB+AOF persistence, noeviction, storage required. Immutable after creation.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"tier": schema.StringAttribute{
				Required:    true,
				Description: "Product tier. single = one node, restarts from disk. ha = Sentinel topology, needs a Sentinel-aware client driver. sharded = cluster topology, needs a cluster-aware client driver.",
			},
			"allowedips": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Description: "CIDR allowlist for external access. Required non-empty while external is enabled.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"authenabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"backupenabled": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Store purpose only.",
			},
			"backupschedule": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Backup cron schedule. Retention is fixed at seven days of snapshots.",
			},
			"config": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Description: "Allowlisted Valkey configuration keys. Unknown keys are rejected naming the key.",
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
			},
			"defaulthostname": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Server-generated default hostname (use the hostname generator endpoint). Assigned on create, immutable thereafter.",
			},
			"externalenabled": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Expose the instance at the platform edge. Requires TLS, auth and a non-empty IP allowlist.",
			},
			"hostnames": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"hostname": schema.StringAttribute{
							Required: true,
						},
					},
				},
				Optional:    true,
				Computed:    true,
				Description: "Custom hostnames. A custom hostname on TCP is a vanity name, not a trust upgrade — clients trust the instance CA either way.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"maxmemorypolicy": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Eviction policy. Defaults from purpose (cache = allkeys-lru, store = noeviction) and remains freely settable.",
			},
			"networkpolicies": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Description: "Network policies narrowed to this Valkey instance, referenced by handle.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"password": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Sensitive:   true,
				Description: "Optional. Omitted on create, the platform generates one. Never returned; use the credentials endpoint to reveal it once.",
			},
			"project": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"shards": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Sharded tier only. Grow-only in self-service: raising it is automated, lowering it is an operator procedure raised through a support ticket.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"size": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Size axis for the ha and sharded tiers (standard is the default). Not applicable to single.",
			},
			"storagegb": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Persistent storage per node in GB. Required for purpose store, not applicable to cache.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"tlsbundle": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Handle of a customer TLS bundle to serve. Omitted with TLS enabled, the platform issues and manages a bundle in your vault. A supplied bundle must cover every hostname the instance answers to; a 400 lists any missing names.",
			},
			"tlsenabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"nodes": schema.Int64Attribute{
				Computed:    true,
				Description: "Derived node count per region for the current tier, size and shards.",
				// No UseStateForUnknown: the count changes on update (tier, size or shards growth); pinning the prior value would make such applies fail as inconsistent.
			},
			"organisation": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"projectname": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"status": schema.StringAttribute{
				Computed: true,
				// No UseStateForUnknown: status legitimately moves on update (error -> provisioning -> running); pinning the prior value would make recovery applies fail as inconsistent.
			},
		},
	}
}

func (r *valkeyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *valkeyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan valkeyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	handle := plan.Handle.ValueString()
	exists, err := r.client.HandleExists(ctx, "valkey-handle", handle)
	if err != nil {
		resp.Diagnostics.AddError("Handle existence check failed", err.Error())
		return
	}
	if exists {
		resp.Diagnostics.AddError(
			"Handle already in use",
			fmt.Sprintf("A valkey with handle %q already exists in this organisation. Handles cannot be reused.", handle),
		)
		return
	}

	body, diags := planToValkeyPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPost, fmt.Sprintf("/organisations/%s/valkey", r.client.OrganisationID()), body)
	if err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status from Create", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	var id string
	if err := json.Unmarshal(data, &id); err != nil {
		resp.Diagnostics.AddError("Decode created id failed", err.Error())
		return
	}

	// 20min headroom: a deploy can spend up to ~5min in the platform's
	// wait-for-bahriya-secrets gate (30×10s) before helm/health checks even start.
	createTimeout := 20 * time.Minute
	_, werr := lifecycle.WaitForStatus(ctx, func(ctx context.Context) (string, error) {
		fresh, d := r.fetch(ctx, id)
		if d.HasError() {
			return "", fmt.Errorf("fetch error during wait")
		}
		return fresh.Status.ValueString(), nil
	}, lifecycle.WaitOptions{
		Target:   "running",
		Terminal: []string{"error"},
		Timeout:  createTimeout,
	})
	if werr != nil {
		// The instance WAS created — the POST returned its id, so the handle is
		// now permanently taken. It merely didn't reach "running" within the wait
		// (still provisioning, or its deploy errored). Do NOT return an error here:
		// an error taints the resource, and Terraform would then destroy + recreate
		// it on the next apply — which fails with 409 because the immutable handle
		// cannot be reused, wedging the whole configuration. Instead persist the
		// resource with its real (non-running) status and WARN. A later `apply`
		// re-reads the status (a slow deploy may since have come up); if it stays
		// "error", the operator investigates and terminates it explicitly. Either
		// way the handle is never orphaned behind a taint.
		partial, d := r.fetch(ctx, id)
		if d.HasError() {
			// Created but unreadable (rare) — surface it so the id isn't lost silently.
			resp.Diagnostics.Append(d...)
			resp.Diagnostics.AddError("Valkey created but could not be read back", werr.Error())
			return
		}
		partial.Password = knownValue(plan.Password, types.StringNull())
		resp.Diagnostics.Append(resp.State.Set(ctx, partial)...)
		resp.Diagnostics.AddWarning(
			"Valkey created but not yet running",
			fmt.Sprintf(
				"Valkey %q was created but did not reach \"running\" within %s (last status %q). "+
					"It is saved to state; run `terraform apply` again to re-check once the deploy settles. "+
					"If it stays in \"error\", investigate the deploy and terminate the instance explicitly — it "+
					"is not auto-replaced, because the handle is immutable and cannot be reused.",
				handle, createTimeout, partial.Status.ValueString(),
			),
		)
		return
	}

	state, diags := r.fetch(ctx, id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	state.Password = knownValue(plan.Password, types.StringNull())

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *valkeyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state valkeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	if diags.HasError() {
		if diagsContainNotFound(diags) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.Append(diags...)
		return
	}
	fresh.Password = state.Password

	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *valkeyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state valkeyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if valkeyModelsEqual(plan, state) {
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	}

	body, diags := planToValkeyPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPut, fmt.Sprintf("/organisations/%s/valkey/%s", r.client.OrganisationID(), state.ID.ValueString()), body)
	if err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	if status != http.StatusOK {
		// Surface the API's message body (e.g. a 409 explaining a network policy is
		// already project-attached) so the user can act on it, not just the code.
		resp.Diagnostics.AddError("Unexpected status from Update", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	// After a PUT, status-bearing resources transition through a transient
	// "provisioning" state while the backend rolls out the change. Waiting
	// for a stable status here avoids "inconsistent result after apply" when
	// the post-PUT fetch races the rollout.
	updateTimeout := 20 * time.Minute
	_, werr := lifecycle.WaitForStatus(ctx, func(ctx context.Context) (string, error) {
		fresh, d := r.fetch(ctx, state.ID.ValueString())
		if d.HasError() {
			return "", fmt.Errorf("fetch error during wait")
		}
		return fresh.Status.ValueString(), nil
	}, lifecycle.WaitOptions{
		Target:   "running",
		Terminal: []string{"error"},
		Timeout:  updateTimeout,
	})
	if werr != nil {
		// Mirror Create: the PUT was accepted, so the change IS in flight. A slow
		// converge must not fail the apply — erroring here leaves state stale and
		// re-issues the same PUT on every retry for no benefit. Persist the real
		// (non-running) state and WARN; a later apply re-reads the status once the
		// deploy settles.
		partial, d := r.fetch(ctx, state.ID.ValueString())
		if d.HasError() {
			resp.Diagnostics.Append(d...)
			resp.Diagnostics.AddError("Valkey updated but could not be read back", werr.Error())
			return
		}
		partial.Password = knownValue(plan.Password, state.Password)
		resp.Diagnostics.Append(resp.State.Set(ctx, partial)...)
		resp.Diagnostics.AddWarning(
			"Valkey updated but not yet running",
			fmt.Sprintf(
				"The update was accepted but the instance did not reach \"running\" within %s (last status %q). "+
					"It is saved to state; run `terraform apply` again to re-check once the deploy settles.",
				updateTimeout, partial.Status.ValueString(),
			),
		)
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	fresh.Password = knownValue(plan.Password, state.Password)
	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *valkeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state valkeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Status-bearing resources terminate asynchronously. If it's already
	// terminated (torn down out-of-band, or a prior interrupted destroy that has
	// since completed), there's nothing to do. If it's already terminating,
	// don't re-issue terminate — that 4xxs ("cannot be terminated from its
	// current state") — just wait for the terminal state.
	skipTerminate := false
	if raw, ferr := r.fetchRaw(ctx, state.ID.ValueString()); ferr == nil {
		if s, _ := raw["status"].(string); s == "terminated" {
			return
		} else if s == "terminating" {
			skipTerminate = true
		}
	}
	if !skipTerminate {
		_, status, err := r.client.Do(ctx, http.MethodDelete, fmt.Sprintf("/organisations/%s/valkey/%s", r.client.OrganisationID(), state.ID.ValueString()), nil)
		if err != nil && status != http.StatusNotFound {
			resp.Diagnostics.AddError("Delete failed", err.Error())
			return
		}
	}

	deleteTimeout := 20 * time.Minute
	_, werr := lifecycle.WaitForStatus(ctx, func(ctx context.Context) (string, error) {
		raw, ferr := r.fetchRaw(ctx, state.ID.ValueString())
		if ferr != nil {
			return "terminated", nil
		}
		if s, ok := raw["status"].(string); ok {
			return s, nil
		}
		return "terminated", nil
	}, lifecycle.WaitOptions{
		Target:  "terminated",
		Timeout: deleteTimeout,
	})
	if werr != nil {
		resp.Diagnostics.AddError("Resource did not reach terminated status", werr.Error())
		return
	}
}

func (r *valkeyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("id"), req.ID)...)
}

func (r *valkeyResource) fetch(ctx context.Context, id string) (valkeyModel, diagnostics) {
	var diags diagnostics
	data, status, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/valkey/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		if status == http.StatusNotFound {
			diags.AddError("not_found", "resource was deleted out-of-band")
			return valkeyModel{}, diags
		}
		diags.AddError("Fetch failed", err.Error())
		return valkeyModel{}, diags
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		diags.AddError("Decode fetch response failed", err.Error())
		return valkeyModel{}, diags
	}
	return apiToValkeyModel(raw), diags
}

func (r *valkeyResource) fetchRaw(ctx context.Context, id string) (map[string]any, error) {
	data, _, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/valkey/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		return nil, err
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	return raw, nil
}

func planToValkeyPayload(ctx context.Context, m *valkeyModel) (map[string]any, diagnostics) {
	var diags diagnostics
	out := map[string]any{}
	if !m.Handle.IsNull() && !m.Handle.IsUnknown() {
		out["handle"] = m.Handle.ValueString()
	}
	if !m.Activeregions.IsNull() && !m.Activeregions.IsUnknown() {
		var items []string
		diags.Append(m.Activeregions.ElementsAs(ctx, &items, false)...)
		out["activeregions"] = items
	}
	if !m.Memorymb.IsNull() && !m.Memorymb.IsUnknown() {
		out["memorymb"] = m.Memorymb.ValueInt64()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out["name"] = m.Name.ValueString()
	}
	if !m.Purpose.IsNull() && !m.Purpose.IsUnknown() {
		out["purpose"] = m.Purpose.ValueString()
	}
	if !m.Tier.IsNull() && !m.Tier.IsUnknown() {
		out["tier"] = m.Tier.ValueString()
	}
	if !m.Allowedips.IsNull() && !m.Allowedips.IsUnknown() {
		var items []string
		diags.Append(m.Allowedips.ElementsAs(ctx, &items, false)...)
		out["allowedips"] = items
	} else {
		out["allowedips"] = []string{}
	}
	// Unset booleans are OMITTED, never sent as false. These attributes are
	// Optional+Computed, so "absent from config" plans as UNKNOWN — which means
	// "leave it alone", not "set it to false". Sending false here clobbered any
	// value set outside Terraform on every apply, and where the API default is
	// true it inverted the contract outright: valkey `authenabled` defaults to
	// true server-side, so forcing false created UNAUTHENTICATED instances.
	// An explicit `= false` in config still sends false — it is not unknown.
	if !m.Authenabled.IsNull() && !m.Authenabled.IsUnknown() {
		out["authenabled"] = m.Authenabled.ValueBool()
	}
	// Unset booleans are OMITTED, never sent as false. These attributes are
	// Optional+Computed, so "absent from config" plans as UNKNOWN — which means
	// "leave it alone", not "set it to false". Sending false here clobbered any
	// value set outside Terraform on every apply, and where the API default is
	// true it inverted the contract outright: valkey `authenabled` defaults to
	// true server-side, so forcing false created UNAUTHENTICATED instances.
	// An explicit `= false` in config still sends false — it is not unknown.
	if !m.Backupenabled.IsNull() && !m.Backupenabled.IsUnknown() {
		out["backupenabled"] = m.Backupenabled.ValueBool()
	}
	if !m.Backupschedule.IsNull() && !m.Backupschedule.IsUnknown() {
		out["backupschedule"] = m.Backupschedule.ValueString()
	}
	if !m.Config.IsNull() && !m.Config.IsUnknown() {
		kv := map[string]string{}
		diags.Append(m.Config.ElementsAs(ctx, &kv, false)...)
		out["config"] = kv
	}
	if !m.Defaulthostname.IsNull() && !m.Defaulthostname.IsUnknown() {
		out["defaulthostname"] = m.Defaulthostname.ValueString()
	}
	// Unset booleans are OMITTED, never sent as false. These attributes are
	// Optional+Computed, so "absent from config" plans as UNKNOWN — which means
	// "leave it alone", not "set it to false". Sending false here clobbered any
	// value set outside Terraform on every apply, and where the API default is
	// true it inverted the contract outright: valkey `authenabled` defaults to
	// true server-side, so forcing false created UNAUTHENTICATED instances.
	// An explicit `= false` in config still sends false — it is not unknown.
	if !m.Externalenabled.IsNull() && !m.Externalenabled.IsUnknown() {
		out["externalenabled"] = m.Externalenabled.ValueBool()
	}
	if !m.Hostnames.IsNull() && !m.Hostnames.IsUnknown() {
		var nested []valkeyHostnamesModel
		diags.Append(m.Hostnames.ElementsAs(ctx, &nested, false)...)
		items := make([]map[string]any, 0, len(nested))
		for _, n := range nested {
			item := map[string]any{}
			if !n.Hostname.IsNull() && !n.Hostname.IsUnknown() {
				item["hostname"] = n.Hostname.ValueString()
			}
			items = append(items, item)
		}
		out["hostnames"] = items
	} else {
		out["hostnames"] = []map[string]any{}
	}
	if !m.Maxmemorypolicy.IsNull() && !m.Maxmemorypolicy.IsUnknown() {
		out["maxmemorypolicy"] = m.Maxmemorypolicy.ValueString()
	}
	if !m.Networkpolicies.IsNull() && !m.Networkpolicies.IsUnknown() {
		var items []string
		diags.Append(m.Networkpolicies.ElementsAs(ctx, &items, false)...)
		out["networkpolicies"] = items
	} else {
		out["networkpolicies"] = []string{}
	}
	if !m.Password.IsNull() && !m.Password.IsUnknown() {
		out["password"] = m.Password.ValueString()
	}
	if !m.Project.IsNull() && !m.Project.IsUnknown() {
		out["project"] = m.Project.ValueString()
	}
	if !m.Shards.IsNull() && !m.Shards.IsUnknown() {
		out["shards"] = m.Shards.ValueInt64()
	}
	if !m.Size.IsNull() && !m.Size.IsUnknown() {
		out["size"] = m.Size.ValueString()
	}
	if !m.Storagegb.IsNull() && !m.Storagegb.IsUnknown() {
		out["storagegb"] = m.Storagegb.ValueInt64()
	}
	if !m.Tlsbundle.IsNull() && !m.Tlsbundle.IsUnknown() {
		out["tlsbundle"] = m.Tlsbundle.ValueString()
	}
	// Unset booleans are OMITTED, never sent as false. These attributes are
	// Optional+Computed, so "absent from config" plans as UNKNOWN — which means
	// "leave it alone", not "set it to false". Sending false here clobbered any
	// value set outside Terraform on every apply, and where the API default is
	// true it inverted the contract outright: valkey `authenabled` defaults to
	// true server-side, so forcing false created UNAUTHENTICATED instances.
	// An explicit `= false` in config still sends false — it is not unknown.
	if !m.Tlsenabled.IsNull() && !m.Tlsenabled.IsUnknown() {
		out["tlsenabled"] = m.Tlsenabled.ValueBool()
	}
	return out, diags
}

func apiToValkeyModel(raw map[string]any) valkeyModel {
	m := valkeyModel{}
	if v, ok := raw["id"].(string); ok {
		m.ID = types.StringValue(v)
	} else {
		m.ID = types.StringNull()
	}
	if v, ok := raw["handle"].(string); ok {
		m.Handle = types.StringValue(v)
	} else {
		m.Handle = types.StringNull()
	}
	if items, ok := raw["activeregions"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if s, ok := it.(string); ok {
				elements = append(elements, types.StringValue(s))
			}
		}
		listVal, _ := types.ListValue(types.StringType, elements)
		m.Activeregions = listVal
	} else {
		m.Activeregions = types.ListNull(types.StringType)
	}
	if v, ok := raw["memorymb"].(float64); ok {
		m.Memorymb = types.Int64Value(int64(v))
	} else {
		m.Memorymb = types.Int64Null()
	}
	if v, ok := raw["name"].(string); ok {
		m.Name = types.StringValue(v)
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := raw["purpose"].(string); ok {
		m.Purpose = types.StringValue(v)
	} else {
		m.Purpose = types.StringNull()
	}
	if v, ok := raw["tier"].(string); ok {
		m.Tier = types.StringValue(v)
	} else {
		m.Tier = types.StringNull()
	}
	if items, ok := raw["allowedips"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if s, ok := it.(string); ok {
				elements = append(elements, types.StringValue(s))
			}
		}
		listVal, _ := types.ListValue(types.StringType, elements)
		m.Allowedips = listVal
	} else {
		m.Allowedips = types.ListNull(types.StringType)
	}
	if v, ok := raw["authenabled"].(bool); ok {
		m.Authenabled = types.BoolValue(v)
	} else {
		m.Authenabled = types.BoolNull()
	}
	if v, ok := raw["backupenabled"].(bool); ok {
		m.Backupenabled = types.BoolValue(v)
	} else {
		m.Backupenabled = types.BoolNull()
	}
	if v, ok := raw["backupschedule"].(string); ok {
		m.Backupschedule = types.StringValue(v)
	} else {
		m.Backupschedule = types.StringNull()
	}
	if kv, ok := raw["config"].(map[string]any); ok {
		elements := map[string]attr.Value{}
		for k, v := range kv {
			switch t := v.(type) {
			case string:
				elements[k] = types.StringValue(t)
			case float64:
				// API-normalised integer values round-trip as their canonical
				// string form so state matches what the user configured.
				elements[k] = types.StringValue(strconv.FormatInt(int64(t), 10))
			case bool:
				elements[k] = types.StringValue(strconv.FormatBool(t))
			default:
				elements[k] = types.StringValue(fmt.Sprintf("%v", t))
			}
		}
		mapVal, _ := types.MapValue(types.StringType, elements)
		m.Config = mapVal
	} else {
		m.Config = types.MapNull(types.StringType)
	}
	if v, ok := raw["defaulthostname"].(string); ok {
		m.Defaulthostname = types.StringValue(v)
	} else {
		m.Defaulthostname = types.StringNull()
	}
	if v, ok := raw["externalenabled"].(bool); ok {
		m.Externalenabled = types.BoolValue(v)
	} else {
		m.Externalenabled = types.BoolNull()
	}
	if items, ok := raw["hostnames"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if obj, ok := it.(map[string]any); ok {
				attrVals := map[string]attr.Value{}
				if v, ok := obj["hostname"].(string); ok {
					attrVals["hostname"] = types.StringValue(v)
				} else {
					attrVals["hostname"] = types.StringNull()
				}
				objVal, _ := types.ObjectValue(valkeyHostnamesAttrTypes(), attrVals)
				elements = append(elements, objVal)
			}
		}
		listVal, _ := types.ListValue(valkeyHostnamesObjectType(), elements)
		m.Hostnames = listVal
	} else {
		m.Hostnames = types.ListNull(valkeyHostnamesObjectType())
	}
	if v, ok := raw["maxmemorypolicy"].(string); ok {
		m.Maxmemorypolicy = types.StringValue(v)
	} else {
		m.Maxmemorypolicy = types.StringNull()
	}
	if items, ok := raw["networkpolicies"].([]any); ok {
		elements := make([]attr.Value, 0, len(items))
		for _, it := range items {
			if s, ok := it.(string); ok {
				elements = append(elements, types.StringValue(s))
			}
		}
		listVal, _ := types.ListValue(types.StringType, elements)
		m.Networkpolicies = listVal
	} else {
		m.Networkpolicies = types.ListNull(types.StringType)
	}
	if v, ok := raw["password"].(string); ok {
		m.Password = types.StringValue(v)
	} else {
		m.Password = types.StringNull()
	}
	if v, ok := raw["project"].(string); ok {
		m.Project = types.StringValue(v)
	} else {
		m.Project = types.StringNull()
	}
	if v, ok := raw["shards"].(float64); ok {
		m.Shards = types.Int64Value(int64(v))
	} else {
		m.Shards = types.Int64Null()
	}
	if v, ok := raw["size"].(string); ok {
		m.Size = types.StringValue(v)
	} else {
		m.Size = types.StringNull()
	}
	if v, ok := raw["storagegb"].(float64); ok {
		m.Storagegb = types.Int64Value(int64(v))
	} else {
		m.Storagegb = types.Int64Null()
	}
	if v, ok := raw["tlsbundle"].(string); ok {
		m.Tlsbundle = types.StringValue(v)
	} else {
		m.Tlsbundle = types.StringNull()
	}
	if v, ok := raw["tlsenabled"].(bool); ok {
		m.Tlsenabled = types.BoolValue(v)
	} else {
		m.Tlsenabled = types.BoolNull()
	}
	if v, ok := raw["nodes"].(float64); ok {
		m.Nodes = types.Int64Value(int64(v))
	} else {
		m.Nodes = types.Int64Null()
	}
	if v, ok := raw["organisation"].(string); ok {
		m.Organisation = types.StringValue(v)
	} else {
		m.Organisation = types.StringNull()
	}
	if v, ok := raw["projectname"].(string); ok {
		m.Projectname = types.StringValue(v)
	} else {
		m.Projectname = types.StringNull()
	}
	if v, ok := raw["status"].(string); ok {
		m.Status = types.StringValue(v)
	} else {
		m.Status = types.StringNull()
	}
	return m
}

func valkeyHostnamesAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"hostname": types.StringType,
	}
}

func valkeyHostnamesObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: valkeyHostnamesAttrTypes()}
}

func valkeyModelsEqual(a, b valkeyModel) bool {
	if !a.Handle.Equal(b.Handle) {
		return false
	}
	if !a.Activeregions.Equal(b.Activeregions) {
		return false
	}
	if !a.Memorymb.Equal(b.Memorymb) {
		return false
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	if !a.Purpose.Equal(b.Purpose) {
		return false
	}
	if !a.Tier.Equal(b.Tier) {
		return false
	}
	if !a.Allowedips.Equal(b.Allowedips) {
		return false
	}
	if !a.Authenabled.Equal(b.Authenabled) {
		return false
	}
	if !a.Backupenabled.Equal(b.Backupenabled) {
		return false
	}
	if !a.Backupschedule.Equal(b.Backupschedule) {
		return false
	}
	if !a.Config.Equal(b.Config) {
		return false
	}
	if !a.Defaulthostname.Equal(b.Defaulthostname) {
		return false
	}
	if !a.Externalenabled.Equal(b.Externalenabled) {
		return false
	}
	if !a.Hostnames.Equal(b.Hostnames) {
		return false
	}
	if !a.Maxmemorypolicy.Equal(b.Maxmemorypolicy) {
		return false
	}
	if !a.Networkpolicies.Equal(b.Networkpolicies) {
		return false
	}
	if !a.Password.Equal(b.Password) {
		return false
	}
	if !a.Project.Equal(b.Project) {
		return false
	}
	if !a.Shards.Equal(b.Shards) {
		return false
	}
	if !a.Size.Equal(b.Size) {
		return false
	}
	if !a.Storagegb.Equal(b.Storagegb) {
		return false
	}
	if !a.Tlsbundle.Equal(b.Tlsbundle) {
		return false
	}
	if !a.Tlsenabled.Equal(b.Tlsenabled) {
		return false
	}
	return true
}
