// Code generated by cmd/generator. DO NOT EDIT.

package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"

	"github.com/bahriya-cloud/terraform-provider-bahriya/internal/client"
)

var (
	_ resource.Resource                = &yaml_configResource{}
	_ resource.ResourceWithConfigure   = &yaml_configResource{}
	_ resource.ResourceWithImportState = &yaml_configResource{}
)

func NewYAMLConfigResource() resource.Resource {
	return &yaml_configResource{}
}

type yaml_configResource struct {
	client *client.Client
}

type yaml_configModel struct {
	ID                    types.String `tfsdk:"id"`
	Handle                types.String `tfsdk:"handle"`
	Content               types.String `tfsdk:"content"`
	Name                  types.String `tfsdk:"name"`
	Maxversions           types.Int64  `tfsdk:"maxversions"`
	Billable              types.Bool   `tfsdk:"billable"`
	Currentversion        types.Int64  `tfsdk:"currentversion"`
	Managedbyresourceid   types.String `tfsdk:"managedbyresourceid"`
	Managedbyresourcetype types.String `tfsdk:"managedbyresourcetype"`
	Organisation          types.String `tfsdk:"organisation"`
}

func (r *yaml_configResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_yaml_config"
}

func (r *yaml_configResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Bahriya yaml_config.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"handle": schema.StringAttribute{
				Required:    true,
				Description: "DNS-1123 compliant: lowercase alphanumeric and hyphens only.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"content": schema.StringAttribute{
				Required:    true,
				Description: "Valid YAML content.",
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"maxversions": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"billable": schema.BoolAttribute{
				Computed: true,
			},
			"currentversion": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourceid": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"managedbyresourcetype": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"organisation": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *yaml_configResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *yaml_configResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan yaml_configModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	handle := plan.Handle.ValueString()
	exists, err := r.client.HandleExists(ctx, "yaml_config", handle)
	if err != nil {
		resp.Diagnostics.AddError("Handle existence check failed", err.Error())
		return
	}
	if exists {
		resp.Diagnostics.AddError(
			"Handle already in use",
			fmt.Sprintf("A yaml_config with handle %q already exists in this organisation. Handles cannot be reused.", handle),
		)
		return
	}

	body, diags := planToYAMLConfigPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPost, fmt.Sprintf("/organisations/%s/yaml_configs", r.client.OrganisationID()), body)
	if err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	if status == http.StatusConflict {
		// A refusal on project resource limits is the one 409 with a structured body, and it is
		// the one a practitioner can act on: it says which ceiling, in which region, and by how
		// much. Rendering it as raw JSON next to "Unexpected status" would bury that.
		if verdict := client.DecodeQuotaRefusal(data); verdict != nil {
			resp.Diagnostics.AddError("Project resource limits exceeded", client.QuotaDetail(verdict))
			return
		}
	}
	if status != http.StatusCreated {
		resp.Diagnostics.AddError("Unexpected status from Create", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	id, verdict, err := client.DecodeWrite(data)
	if err != nil {
		resp.Diagnostics.AddError("Decode created id failed", err.Error())
		return
	}
	if warning := client.QuotaWarning(verdict); warning != "" {
		// Applied, and running. It may still be unable to reach the replica count the
		// configuration asks for, which nothing else in the plan or state would ever reveal.
		resp.Diagnostics.AddWarning("Scaling limited by project resource limits", warning)
	}

	state, diags := r.fetch(ctx, id)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *yaml_configResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state yaml_configModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	if diags.HasError() {
		if diagsContainNotFound(diags) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.Append(diags...)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *yaml_configResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state yaml_configModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if yaml_configModelsEqual(plan, state) {
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	}

	body, diags := planToYAMLConfigPayload(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	body["organisation"] = r.client.OrganisationID()

	data, status, err := r.client.Do(ctx, http.MethodPut, fmt.Sprintf("/organisations/%s/yaml_configs/%s", r.client.OrganisationID(), state.ID.ValueString()), body)
	if err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	if status != http.StatusOK {
		// Surface the API's message body (e.g. a 409 explaining a network policy is
		// already project-attached) so the user can act on it, not just the code.
		resp.Diagnostics.AddError("Unexpected status from Update", fmt.Sprintf("HTTP %d: %s", status, string(data)))
		return
	}

	fresh, diags := r.fetch(ctx, state.ID.ValueString())
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, fresh)...)
}

func (r *yaml_configResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state yaml_configModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, status, err := r.client.Do(ctx, http.MethodDelete, fmt.Sprintf("/organisations/%s/yaml_configs/%s", r.client.OrganisationID(), state.ID.ValueString()), nil)
	if err != nil && status != http.StatusNotFound {
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

func (r *yaml_configResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, schemaPath("id"), req.ID)...)
}

func (r *yaml_configResource) fetch(ctx context.Context, id string) (yaml_configModel, diagnostics) {
	var diags diagnostics
	data, status, err := r.client.Do(ctx, http.MethodGet, fmt.Sprintf("/organisations/%s/yaml_configs/%s", r.client.OrganisationID(), id), nil)
	if err != nil {
		if status == http.StatusNotFound {
			diags.AddError("not_found", "resource was deleted out-of-band")
			return yaml_configModel{}, diags
		}
		diags.AddError("Fetch failed", err.Error())
		return yaml_configModel{}, diags
	}
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		diags.AddError("Decode fetch response failed", err.Error())
		return yaml_configModel{}, diags
	}
	return apiToYAMLConfigModel(raw), diags
}

func planToYAMLConfigPayload(ctx context.Context, m *yaml_configModel) (map[string]any, diagnostics) {
	var diags diagnostics
	out := map[string]any{}
	if !m.Handle.IsNull() && !m.Handle.IsUnknown() {
		out["handle"] = m.Handle.ValueString()
	}
	if !m.Content.IsNull() && !m.Content.IsUnknown() {
		out["content"] = m.Content.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out["name"] = m.Name.ValueString()
	}
	if !m.Maxversions.IsNull() && !m.Maxversions.IsUnknown() {
		out["maxversions"] = m.Maxversions.ValueInt64()
	}
	return out, diags
}

func apiToYAMLConfigModel(raw map[string]any) yaml_configModel {
	m := yaml_configModel{}
	if v, ok := raw["id"].(string); ok {
		m.ID = types.StringValue(v)
	} else {
		m.ID = types.StringNull()
	}
	if v, ok := raw["handle"].(string); ok {
		m.Handle = types.StringValue(v)
	} else {
		m.Handle = types.StringNull()
	}
	if v, ok := raw["content"].(string); ok {
		m.Content = types.StringValue(v)
	} else {
		m.Content = types.StringNull()
	}
	if v, ok := raw["name"].(string); ok {
		m.Name = types.StringValue(v)
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := raw["maxversions"].(float64); ok {
		m.Maxversions = types.Int64Value(int64(v))
	} else {
		m.Maxversions = types.Int64Null()
	}
	if v, ok := raw["billable"].(bool); ok {
		m.Billable = types.BoolValue(v)
	} else {
		m.Billable = types.BoolNull()
	}
	if v, ok := raw["currentversion"].(float64); ok {
		m.Currentversion = types.Int64Value(int64(v))
	} else {
		m.Currentversion = types.Int64Null()
	}
	if v, ok := raw["managedbyresourceid"].(string); ok {
		m.Managedbyresourceid = types.StringValue(v)
	} else {
		m.Managedbyresourceid = types.StringNull()
	}
	if v, ok := raw["managedbyresourcetype"].(string); ok {
		m.Managedbyresourcetype = types.StringValue(v)
	} else {
		m.Managedbyresourcetype = types.StringNull()
	}
	if v, ok := raw["organisation"].(string); ok {
		m.Organisation = types.StringValue(v)
	} else {
		m.Organisation = types.StringNull()
	}
	return m
}

func yaml_configModelsEqual(a, b yaml_configModel) bool {
	if !a.Handle.Equal(b.Handle) {
		return false
	}
	if !a.Content.Equal(b.Content) {
		return false
	}
	if !a.Name.Equal(b.Name) {
		return false
	}
	if !a.Maxversions.Equal(b.Maxversions) {
		return false
	}
	return true
}
