package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
)

func main() {
	specDir := flag.String("spec", "../packages/bahriya-openapi/specs/v1", "directory containing OpenAPI YAML specs")
	outputDir := flag.String("out", "internal/resources", "directory to write generated resource files to")
	flag.Parse()

	targets := []string{"project", "registry", "secret", "memcached", "container"}

	if err := run(*specDir, *outputDir, targets); err != nil {
		log.Fatal(err)
	}
}

func run(specDir, outputDir string, targets []string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("ensure output dir: %w", err)
	}

	for _, name := range targets {
		desc, ok := descriptors[name]
		if !ok {
			return fmt.Errorf("no descriptor for resource %q", name)
		}
		specPath := filepath.Join(specDir, plural(name)+".yaml")
		res, err := parseResource(specPath, desc)
		if err != nil {
			return err
		}
		if err := render(res, outputDir); err != nil {
			return err
		}
		fmt.Printf("generated %s_resource.go (%d attributes)\n", res.Name, len(res.Attributes))
	}

	if err := writeRegistry(outputDir, targets); err != nil {
		return err
	}
	return nil
}

// plural is a tiny helper: spec filenames are pluralised (projects.yaml,
// containers.yaml). Naive 'add s' is good enough for the five resources we
// have; replace with an irregularity map if that changes.
func plural(s string) string {
	switch s {
	case "memcached":
		return "memcached"
	case "registry":
		return "registries"
	}
	return s + "s"
}

// writeRegistry emits internal/resources/registry.go which exposes a
// Resources() slice the provider can plug into framework wiring.
func writeRegistry(outputDir string, names []string) error {
	const tmpl = `// Code generated by cmd/generator. DO NOT EDIT.

package resources

import "github.com/hashicorp/terraform-plugin-framework/resource"

// All returns the set of resource constructors for the Bahriya provider.
// Append to this slice as new resources are generated.
func All() []func() resource.Resource {
	return []func() resource.Resource{
%s	}
}
`
	var body string
	for _, n := range names {
		body += fmt.Sprintf("\t\tNew%sResource,\n", pascalCase(n))
	}
	out := fmt.Sprintf(tmpl, body)
	return os.WriteFile(filepath.Join(outputDir, "registry.go"), []byte(out), 0o644)
}
